// The entire site's content lives here. Add categories and tools by editing this file.
// Tools within each category are ordered by demand (highest first). Paid/API tools
// (see COST notes) are placed LAST in their category so they land in the final build rounds.
// "Round N" of the launch plan = the Nth tool in each category.
// status: "live" | "soon".  tool.built: true once the tool actually works (until then its
// page is a "coming soon" stub, set to noindex).

// Canonical origin for the whole site (metadataBase, canonicals, og:url, sitemap, robots).
// Override with NEXT_PUBLIC_SITE_URL in Vercel if the custom domain isn't live yet,
// e.g. NEXT_PUBLIC_SITE_URL=https://everyboringtool.vercel.app
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://everyboringtool.com").replace(/\/+$/, "");

export const SITE = {
  name: "Every Boring Tool",
  short: "EBT",
  domain: SITE_URL.replace(/^https?:\/\//, ""),
  url: SITE_URL,
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "contact@everyboringtool.com",
  tagline: "Everything simple and boring.",
  description:
    "Every boring tool you need, in one simple place. Free, fast, and no sign-up — everything runs right in your browser.",
};

// Honest site-wide "content last reviewed" date, used for schema.org dateModified
// on tool pages. Kept as a hand-set constant (NOT the deploy date) so we only
// claim freshness when the content was actually touched — bump this when tool
// copy/FAQs are meaningfully updated. A per-tool `updated` field in toolContent
// overrides it where a single tool is revised on its own.
export const LAST_UPDATED = "2026-08-26";

// Categories are defined below in their natural grouping. The exported
// `categories` is a reordered view (see MENU_ORDER after the array) so the whole
// site — top menu, homepage tiles and footer — shows the same custom order.
const rawCategories = [
  {
    slug: "party",
    name: "Party Games",
    short: "Party",
    emoji: "\u{1F389}",
    description: "Team pickers, party-game generators, icebreakers and more.",
    status: "soon",
    tools: [
      { slug: "team-generator", name: "Team Generator", description: "Split names into random teams.", popular: true },
      { slug: "truth-or-dare", name: "Truth or Dare Generator", description: "Random truths and dares." },
      { slug: "would-you-rather", name: "Would You Rather Generator", description: "Random would-you-rather dilemmas." },
      { slug: "never-have-i-ever", name: "Never Have I Ever Generator", description: "Random statements to play." },
      { slug: "charades-generator", name: "Charades Word Generator", description: "Random words and phrases to act out." },
      { slug: "bingo-card-generator", name: "Bingo Card Generator", description: "Printable bingo cards, numbers or words." },
      { slug: "pictionary-generator", name: "Pictionary Word Generator", description: "Random words to draw." },
      { slug: "trivia-generator", name: "Trivia Question Generator", description: "Random trivia questions by category." },
      { slug: "spin-the-bottle", name: "Spin the Bottle", description: "An animated spinner for the classic game." },
      { slug: "team-name-generator", name: "Team Name Generator", description: "Random funny team names." },
      { slug: "secret-santa-generator", name: "Secret Santa Generator", description: "Draw names for a gift exchange." },
      { slug: "most-likely-to", name: "Who's Most Likely To Generator", description: "Random party prompts." },
      { slug: "icebreaker-generator", name: "Icebreaker Question Generator", description: "Random conversation starters." },
      { slug: "mafia-role-assigner", name: "Mafia Role Assigner", description: "Deal secret roles to players." },
      { slug: "scattergories-generator", name: "Scattergories Generator", description: "Random letter and category list." },
      { slug: "heads-up-generator", name: "Heads Up Word Generator", description: "Random words to guess out loud." },
      { slug: "group-scoreboard", name: "Group Scoreboard", description: "Track scores for players or teams." },
      { slug: "random-turn-order", name: "Random Turn Order", description: "Shuffle who goes first." },
    ],
  },
  {
    slug: "pdf",
    name: "PDF Tools",
    short: "PDF",
    emoji: "\u{1F4C4}",
    description: "Merge, split, compress and convert PDFs — right in your browser.",
    status: "live",
    tools: [
      { slug: "merge-pdf", name: "Merge PDF", description: "Combine several PDFs into one file.", popular: true },
      { slug: "compress-pdf", name: "Compress PDF", description: "Shrink PDF size without wrecking quality." },
      { slug: "split-pdf", name: "Split PDF", description: "Separate a PDF into pages or ranges." },
      { slug: "word-to-pdf", name: "Word to PDF", description: "Convert a Word document to a PDF.", popular: true },
      { slug: "pdf-to-jpg", name: "PDF to JPG", description: "Turn each PDF page into an image." },
      { slug: "jpg-to-pdf", name: "JPG to PDF", description: "Combine images into a single PDF." },
      { slug: "rotate-pdf", name: "Rotate PDF", description: "Turn pages the right way up and save." },
      { slug: "protect-pdf", name: "Protect PDF", description: "Add a password to keep a PDF private." },
      { slug: "reorder-pages", name: "Reorder Pages", description: "Drag pages into the order you want." },
      { slug: "add-page-numbers", name: "Add Page Numbers", description: "Insert page numbers into a PDF." },
      { slug: "watermark-pdf", name: "Watermark PDF", description: "Stamp text or a logo across pages." },
      { slug: "pdf-to-png", name: "PDF to PNG", description: "Turn each PDF page into a PNG image." },
      { slug: "pdf-to-text", name: "PDF to Text", description: "Extract the text from a PDF." },
      { slug: "delete-pdf-pages", name: "Delete PDF Pages", description: "Remove chosen pages from a PDF." },
      { slug: "extract-pdf-pages", name: "Extract PDF Pages", description: "Pull a page range into a new PDF." },
      { slug: "crop-pdf", name: "Crop PDF", description: "Trim the margins of every page." },
      { slug: "add-text-to-pdf", name: "Add Text to PDF", description: "Add a line of text to a page." },
      { slug: "esign-pdf", name: "Sign PDF", description: "Draw a signature and place it." },
      { slug: "create-pdf", name: "Create PDF", description: "Make a PDF from typed text." },
      { slug: "extract-pdf-images", name: "Extract Images from PDF", description: "Pull embedded images out of a PDF." },
      { slug: "reverse-pdf-pages", name: "Reverse PDF Pages", description: "Flip a PDF's page order." },
    ],
  },
  {
    slug: "image",
    name: "Image Tools",
    short: "Image",
    emoji: "\u{1F5BC}\u{FE0F}",
    description: "Compress, resize, convert and crop images in seconds.",
    status: "soon",
    tools: [
      { slug: "image-compressor", name: "Image Compressor", description: "Shrink image file size.", popular: true },
      { slug: "pfp-maker", name: "PFP Maker", description: "Turn a photo into a clean profile picture.", popular: true },
      { slug: "image-resizer", name: "Image Resizer", description: "Resize to any dimensions." },
      { slug: "crop-image", name: "Crop Image", description: "Crop to a shape or ratio." },
      { slug: "png-to-jpg", name: "PNG to JPG", description: "Convert PNG images to JPG." },
      { slug: "jpg-to-png", name: "JPG to PNG", description: "Convert JPG images to PNG." },
      { slug: "image-to-webp", name: "Image to WebP", description: "Convert JPG/PNG to WebP." },
      { slug: "heic-to-jpg", name: "HEIC to JPG", description: "Convert iPhone HEIC photos." },
      { slug: "rotate-image", name: "Rotate & Flip", description: "Rotate or mirror an image." },
      { slug: "image-to-text", name: "Image to Text (OCR)", description: "Extract text from an image." },
      { slug: "webp-to-png", name: "WebP to PNG", description: "Convert WebP back to PNG." },
      { slug: "svg-to-png", name: "SVG to PNG", description: "Rasterize SVG to PNG." },
      { slug: "favicon-generator", name: "Favicon Generator", description: "Make a favicon from an image." },
      { slug: "image-to-base64", name: "Image to Base64", description: "Encode an image as text." },
      { slug: "meme-generator", name: "Meme Generator", description: "Add top/bottom text to images." },
      { slug: "black-and-white", name: "Black & White", description: "Turn a photo greyscale." },
      { slug: "sepia-image", name: "Sepia Photo", description: "Add a warm vintage tone." },
      { slug: "invert-colors", name: "Invert Colors", description: "Make a photo negative." },
      { slug: "brightness-contrast", name: "Brightness & Contrast", description: "Adjust brightness and contrast." },
      { slug: "blur-image", name: "Blur Image", description: "Soften an image or hide detail." },
      { slug: "sharpen-image", name: "Sharpen Image", description: "Sharpen a soft or blurry photo." },
      { slug: "pixelate-image", name: "Pixelate Image", description: "Add a pixel or mosaic effect." },
      { slug: "add-border-to-image", name: "Add Border to Image", description: "Add a colored frame." },
      { slug: "add-text-to-image", name: "Add Text to Image", description: "Add a caption to an image." },
      { slug: "round-image", name: "Round Image", description: "Crop to a circle for a profile pic." },
      { slug: "webp-to-jpg", name: "WebP to JPG", description: "Convert a WebP image to JPG." },
      { slug: "combine-images", name: "Combine Images", description: "Merge images into one." },
      { slug: "collage-maker", name: "Collage Maker", description: "Arrange photos into a grid." },
      { slug: "image-splitter", name: "Image Splitter", description: "Split an image into a grid of tiles." },
      { slug: "exif-viewer", name: "EXIF Viewer", description: "See a photo's metadata and GPS." },
      { slug: "chart-maker", name: "Chart Maker", description: "Turn numbers into a bar chart image." },
    ],
  },
  {
    slug: "calculators",
    name: "Calculators",
    short: "Calculators",
    emoji: "\u{1F522}",
    description: "Percentages, BMI, tips, discounts — quick everyday answers.",
    status: "soon",
    tools: [
      { slug: "percentage-calculator", name: "Percentage Calculator", description: "Work out any percentage." },
      { slug: "bmi-calculator", name: "BMI Calculator", description: "Body mass index." },
      { slug: "tip-calculator", name: "Tip Calculator", description: "Split the bill and tip." },
      { slug: "discount-calculator", name: "Discount Calculator", description: "Price after a discount." },
      { slug: "average-calculator", name: "Average Calculator", description: "Mean, median and mode." },
      { slug: "scientific-calculator", name: "Scientific Calculator", description: "Full scientific calculator." },
      { slug: "random-number-generator", name: "Random Number Generator", description: "Pick random numbers." },
      { slug: "ratio-calculator", name: "Ratio Calculator", description: "Solve and scale ratios." },
      { slug: "fraction-calculator", name: "Fraction Calculator", description: "Add and simplify fractions." },
      { slug: "calorie-calculator", name: "Calorie Calculator", description: "Daily calorie needs." },
    ],
  },
  {
    slug: "text",
    name: "Text & Writing",
    short: "Text",
    emoji: "\u{270D}\u{FE0F}",
    description: "Counters, case converters, unscramblers and text cleanup.",
    status: "soon",
    tools: [
      { slug: "word-counter", name: "Word Counter", description: "Count words and characters.", popular: true },
      { slug: "character-counter", name: "Character Counter", description: "Count characters with limits." },
      { slug: "case-converter", name: "Case Converter", description: "UPPER, lower, Title, Sentence." },
      { slug: "fancy-font-generator", name: "Fancy Font Generator", description: "Bold/italic unicode text." },
      { slug: "lorem-ipsum-generator", name: "Lorem Ipsum Generator", description: "Generate placeholder text." },
      { slug: "text-diff", name: "Text Diff Checker", description: "Compare two blocks of text." },
      { slug: "find-and-replace", name: "Find & Replace", description: "Bulk find and replace text." },
      { slug: "sort-lines", name: "Sort Lines", description: "Sort lines alphabetically." },
      { slug: "remove-duplicate-lines", name: "Remove Duplicate Lines", description: "Delete repeated lines." },
      { slug: "slugify", name: "Slug Generator", description: "Make URL-friendly slugs." },
      { slug: "text-reverser", name: "Text Reverser", description: "Reverse text or words." },
      { slug: "morse-code-translator", name: "Morse Code Translator", description: "Text to and from Morse." },
      { slug: "html-to-text", name: "HTML to Text", description: "Strip tags to plain text." },
    ],
  },
  {
    slug: "converters",
    name: "Converters",
    short: "Converters",
    emoji: "\u{1F504}",
    description: "Units, colors, bases, data formats and currency.",
    status: "soon",
    tools: [
      { slug: "unit-converter", name: "Unit Converter", description: "Convert any common unit." },
      { slug: "length-converter", name: "Length Converter", description: "Metric and imperial length." },
      { slug: "temperature-converter", name: "Temperature Converter", description: "Celsius, Fahrenheit, Kelvin." },
      { slug: "weight-converter", name: "Weight Converter", description: "Kg, lb, oz and more." },
      { slug: "color-converter", name: "Color Converter", description: "HEX, RGB and HSL." },
      { slug: "number-base-converter", name: "Base Converter", description: "Binary, hex, decimal, octal." },
      { slug: "roman-numeral-converter", name: "Roman Numerals", description: "Numbers to Roman numerals." },
      { slug: "number-to-words", name: "Number to Words", description: "Spell out any number." },
      { slug: "clothing-size-converter", name: "Clothing Size Converter", description: "US, UK, EU sizes by country." },
      { slug: "ring-size-converter", name: "Ring Size Converter", description: "US, UK, EU, Japan & mm." },
      { slug: "bra-size-converter", name: "Bra Size Converter", description: "US, UK, EU, FR, AU sizes." },
      { slug: "drill-bit-size-converter", name: "Drill Bit Size Converter", description: "Fraction, metric, letter, number." },
      { slug: "knitting-crochet-converter", name: "Knitting & Crochet Sizes", description: "Needle & hook: US, UK, mm." },
      { slug: "cups-to-grams-converter", name: "Cups to Grams Converter", description: "By ingredient — flour, sugar, etc." },
      { slug: "oven-temperature-converter", name: "Oven Temperature Converter", description: "°F, °C, gas mark & fan." },
      { slug: "pan-size-converter", name: "Cake Pan Size Converter", description: "Swap round, square & rectangular tins." },
      { slug: "yeast-converter", name: "Yeast Converter", description: "Active dry, instant & fresh yeast." },
      { slug: "paper-size-converter", name: "Paper Size Converter", description: "A4, Letter, B & C series." },
      { slug: "kids-clothing-size-converter", name: "Kids Clothing Size Converter", description: "Baby & kids US, UK, EU." },
      { slug: "thread-size-converter", name: "Thread Size Converter", description: "Tex, denier, Nm, ticket." },
      { slug: "bead-size-converter", name: "Bead Size Converter", description: "Seed bead aught to mm." },
    ],
  },
  {
    slug: "data",
    name: "Data",
    short: "Data",
    emoji: "\u{1F5C3}\u{FE0F}",
    description: "Convert between CSV, JSON, XML, YAML, Excel and more — data & file formats.",
    status: "live",
    tools: [
      { slug: "csv-to-json", name: "CSV to JSON", description: "Convert CSV into JSON." },
      { slug: "json-to-csv", name: "JSON to CSV", description: "Convert JSON into CSV." },
      { slug: "markdown-to-html", name: "Markdown to HTML", description: "Render Markdown as HTML." },
      { slug: "xml-to-json", name: "XML to JSON", description: "Convert XML into JSON." },
      { slug: "json-to-xml", name: "JSON to XML", description: "Convert JSON into XML." },
      { slug: "xml-to-csv", name: "XML to CSV", description: "Turn XML records into CSV." },
      { slug: "csv-to-xml", name: "CSV to XML", description: "Turn CSV rows into XML." },
      { slug: "csv-to-markdown", name: "CSV to Markdown", description: "CSV into a Markdown table." },
      { slug: "csv-to-html", name: "CSV to HTML Table", description: "CSV into an HTML table." },
      { slug: "html-table-to-csv", name: "HTML Table to CSV", description: "Pull a table out of HTML as CSV." },
      { slug: "csv-to-excel", name: "CSV to Excel", description: "CSV into an .xlsx spreadsheet." },
      { slug: "excel-to-csv", name: "Excel to CSV", description: "An .xlsx or .xls into CSV." },
      { slug: "excel-to-json", name: "Excel to JSON", description: "A spreadsheet into JSON." },
      { slug: "json-to-excel", name: "JSON to Excel", description: "JSON into an .xlsx spreadsheet." },
      { slug: "excel-to-html", name: "Excel to HTML Table", description: "A spreadsheet into an HTML table." },
      { slug: "split-csv", name: "Split CSV", description: "Split a big CSV into smaller files." },
      { slug: "tsv-to-csv", name: "TSV to CSV", description: "Tab-separated into comma-separated." },
      { slug: "csv-to-tsv", name: "CSV to TSV", description: "Comma-separated into tab-separated." },
      { slug: "yaml-to-json", name: "YAML to JSON", description: "Convert YAML into JSON." },
      { slug: "json-to-yaml", name: "JSON to YAML", description: "Convert JSON into YAML." },
    ],
  },
  {
    slug: "qr-barcode",
    name: "QR & Barcode",
    short: "QR",
    emoji: "\u{1F533}",
    description: "Generate and scan QR codes and barcodes of every kind.",
    status: "soon",
    tools: [
      { slug: "qr-code-generator", name: "QR Code Generator", description: "Make a QR code for anything.", popular: true },
      { slug: "wifi-qr-generator", name: "Wi-Fi QR Generator", description: "Share Wi-Fi with a scan." },
      { slug: "qr-code-scanner", name: "QR Code Scanner", description: "Scan a QR from a photo." },
      { slug: "url-qr-generator", name: "URL QR Generator", description: "QR for any link." },
      { slug: "vcard-qr-generator", name: "vCard QR Generator", description: "A QR contact card." },
      { slug: "whatsapp-qr-generator", name: "WhatsApp QR Generator", description: "QR to a WhatsApp chat." },
      { slug: "barcode-generator", name: "Barcode Generator", description: "Create common barcodes." },
      { slug: "email-qr-generator", name: "Email QR Generator", description: "QR that opens an email." },
    ],
  },
  {
    slug: "datetime",
    name: "Date & Time",
    short: "Date & Time",
    emoji: "\u{23F1}\u{FE0F}",
    description: "Ages, date maths, countdowns, timers and time zones.",
    status: "soon",
    tools: [
      { slug: "age-calculator", name: "Age Calculator", description: "Age from a birth date.", popular: true },
      { slug: "countdown-timer", name: "Countdown Timer", description: "Count down to a date." },
      { slug: "date-difference", name: "Date Difference", description: "Days between two dates." },
      { slug: "pomodoro-timer", name: "Pomodoro Timer", description: "Focus in 25-minute blocks." },
      { slug: "stopwatch", name: "Stopwatch", description: "Simple online stopwatch." },
      { slug: "business-days-calculator", name: "Business Days Calculator", description: "Working days between dates." },
      { slug: "work-hours-calculator", name: "Work Hours Calculator", description: "Hours from a timesheet." },
      { slug: "week-number", name: "Week Number", description: "Find the current week number." },
      { slug: "add-subtract-days", name: "Add or Subtract Days", description: "Shift a date by N days." },
      { slug: "time-zone-converter", name: "Live Clock & Time Zone Converter", description: "Live local clock, plus convert times worldwide." },
    ],
  },
  {
    slug: "finance",
    name: "Finance",
    short: "Finance",
    emoji: "\u{1F4B0}",
    description: "Loan, mortgage, interest, tax and investment calculators.",
    status: "soon",
    tools: [
      { slug: "loan-calculator", name: "Loan / EMI Calculator", description: "Monthly loan payments." },
      { slug: "mortgage-calculator", name: "Mortgage Calculator", description: "Home loan repayments." },
      { slug: "compound-interest-calculator", name: "Compound Interest", description: "Growth over time." },
      { slug: "salary-calculator", name: "Salary Calculator", description: "Hourly to annual pay." },
      { slug: "sip-calculator", name: "SIP Calculator", description: "Systematic investment returns." },
      { slug: "gst-vat-calculator", name: "GST / VAT Calculator", description: "Add or remove tax." },
      { slug: "simple-interest-calculator", name: "Simple Interest", description: "Flat interest maths." },
      { slug: "roi-calculator", name: "ROI Calculator", description: "Return on investment." },
      { slug: "inflation-calculator", name: "Inflation Calculator", description: "Value of money over time." },
      { slug: "savings-goal-calculator", name: "Savings Goal Calculator", description: "Reach a savings target." },
    ],
  },
  {
    slug: "developer",
    name: "Developer",
    short: "Developer",
    emoji: "\u{1F468}\u{200D}\u{1F4BB}",
    description: "JSON, regex, hashes, encoders, formatters and generators.",
    status: "soon",
    tools: [
      { slug: "json-formatter", name: "JSON Formatter", description: "Format and validate JSON.", popular: true },
      { slug: "base64-encode-decode", name: "Base64 Encode / Decode", description: "Convert to and from Base64." },
      { slug: "password-generator", name: "Password Generator", description: "Strong random passwords." },
      { slug: "hash-generator", name: "Hash Generator", description: "MD5, SHA-1, SHA-256." },
      { slug: "url-encode-decode", name: "URL Encode / Decode", description: "Escape and unescape URLs." },
      { slug: "uuid-generator", name: "UUID Generator", description: "Generate unique IDs." },
      { slug: "regex-tester", name: "Regex Tester", description: "Test regular expressions." },
      { slug: "jwt-decoder", name: "JWT Decoder", description: "Decode a JSON web token." },
      { slug: "color-picker", name: "Color Picker", description: "Pick and copy colors." },
      { slug: "html-minifier", name: "HTML Minifier", description: "Shrink HTML markup." },
      { slug: "css-minifier", name: "CSS Minifier", description: "Shrink CSS files." },
      { slug: "js-minifier", name: "JS Minifier", description: "Shrink JavaScript." },
      { slug: "cron-generator", name: "Cron Generator", description: "Build cron expressions." },
      { slug: "json-minify", name: "JSON Minify & Beautify", description: "Minify or beautify JSON." },
      { slug: "epoch-converter", name: "Epoch Converter", description: "Unix timestamp to date and back." },
      { slug: "url-parser", name: "URL Parser", description: "Break a URL into its parts." },
      { slug: "create-zip", name: "Create ZIP File", description: "Bundle files into a .zip archive." },
    ],
  },
  {
    slug: "seo-web",
    name: "SEO & Web",
    short: "SEO",
    emoji: "\u{1F4C8}",
    description: "Meta tags, schema, sitemaps and search-preview tools.",
    status: "soon",
    tools: [
      { slug: "meta-tag-generator", name: "Meta Tag Generator", description: "Build SEO meta tags." },
      { slug: "keyword-density-checker", name: "Keyword Density Checker", description: "Analyze keyword usage." },
      { slug: "serp-snippet-preview", name: "SERP Snippet Preview", description: "Preview a Google result." },
      { slug: "schema-generator", name: "Schema Generator", description: "JSON-LD structured data." },
      { slug: "robots-txt-generator", name: "Robots.txt Generator", description: "Create a robots.txt file." },
      { slug: "slug-generator", name: "URL Slug Generator", description: "SEO-friendly URL slugs." },
      { slug: "canonical-tag-generator", name: "Canonical Tag Generator", description: "Build canonical tags." },
      { slug: "llms-txt-generator", name: "llms.txt Generator", description: "Guide AI crawlers." },
    ],
  },
  {
    slug: "marketing",
    name: "Marketing & Business",
    short: "Marketing",
    emoji: "\u{1F4E3}",
    description: "Margins, ROAS, break-even and campaign tools.",
    status: "soon",
    tools: [
      { slug: "profit-margin-calculator", name: "Profit Margin Calculator", description: "Margin and profit." },
      { slug: "roas-calculator", name: "ROAS Calculator", description: "Return on ad spend." },
      { slug: "markup-calculator", name: "Markup Calculator", description: "Price from cost + markup." },
      { slug: "break-even-calculator", name: "Break-even Calculator", description: "Units to break even." },
      { slug: "conversion-rate-calculator", name: "Conversion Rate Calculator", description: "Conversions ÷ visitors." },
      { slug: "cpm-calculator", name: "CPM Calculator", description: "Cost per thousand impressions." },
      { slug: "cac-calculator", name: "CAC Calculator", description: "Customer acquisition cost." },
      { slug: "cpa-calculator", name: "CPA Calculator", description: "Cost per acquisition." },
      { slug: "utm-builder", name: "UTM Builder", description: "Tag campaign links." },
      { slug: "landing-page-roi-calculator", name: "Landing Page ROI", description: "Traffic to revenue." },
      { slug: "email-subject-line-tester", name: "Subject Line Tester", description: "Score an email subject." },
    ],
  },
  {
    slug: "social",
    name: "Social Media",
    short: "Social",
    emoji: "\u{1F4F1}",
    description: "Resizers, hashtags, captions and creator utilities.",
    status: "soon",
    tools: [
      { slug: "instagram-image-resizer", name: "Instagram Image Resizer", description: "Perfect post/story sizes." },
      { slug: "hashtag-generator", name: "Hashtag Generator", description: "Relevant hashtags fast." },
      { slug: "tweet-character-counter", name: "Tweet Character Counter", description: "Count against the limit." },
      { slug: "bio-character-counter", name: "Bio Character Counter", description: "Fit platform bio limits." },
      { slug: "caption-formatter", name: "Caption Formatter", description: "Add line breaks for IG." },
      { slug: "youtube-thumbnail-resizer", name: "YouTube Thumbnail Resizer", description: "Resize to 1280×720." },
      { slug: "engagement-rate-calculator", name: "Engagement Rate Calculator", description: "Rate from likes/followers." },
      { slug: "link-in-bio-qr", name: "Link-in-Bio QR", description: "QR to your bio link." },
    ],
  },
  {
    slug: "ecommerce",
    name: "E-commerce",
    short: "E-commerce",
    emoji: "\u{1F6D2}",
    description: "Seller fee, margin and pricing calculators.",
    status: "soon",
    tools: [
      { slug: "amazon-margin-calculator", name: "Amazon Margin Calculator", description: "FBA fees and margin." },
      { slug: "shopify-fee-calculator", name: "Shopify Fee Calculator", description: "Fees and net payout." },
      { slug: "etsy-fee-calculator", name: "Etsy Fee Calculator", description: "Listing and payment fees." },
      { slug: "price-after-fees-calculator", name: "Price After Fees", description: "What you actually keep." },
      { slug: "dropshipping-profit-calculator", name: "Dropshipping Profit", description: "Profit per order." },
      { slug: "sku-generator", name: "SKU Generator", description: "Structured product SKUs." },
      { slug: "product-title-counter", name: "Product Title Counter", description: "Fit marketplace limits." },
    ],
  },
  {
    slug: "games",
    name: "Games",
    short: "Games",
    emoji: "\u{1F3AE}",
    description: "Sudoku, typing tests, word games and quick classics.",
    status: "soon",
    tools: [
      { slug: "sudoku", name: "Sudoku", description: "Classic number puzzle." },
      { slug: "typing-speed-test", name: "Typing Speed Test", description: "Measure your WPM." },
      { slug: "2048", name: "2048", description: "Slide tiles to 2048." },
      { slug: "wordle", name: "Wordle", description: "Guess the daily word." },
      { slug: "minesweeper", name: "Minesweeper", description: "The classic mine puzzle." },
      { slug: "solitaire", name: "Solitaire", description: "Klondike solitaire." },
      { slug: "reaction-time-test", name: "Reaction Time Test", description: "How fast are you?" },
      { slug: "cps-test", name: "Click Speed Test", description: "Clicks per second." },
      { slug: "hangman", name: "Hangman", description: "Guess the hidden word." },
      { slug: "word-search", name: "Word Search", description: "Find the hidden words." },
      { slug: "memory-match", name: "Memory Match", description: "Flip and match pairs." },
      { slug: "tic-tac-toe", name: "Tic-Tac-Toe", description: "Play vs an unbeatable AI." },
      { slug: "yes-no-wheel", name: "Yes or No Wheel", description: "Spin for a random yes or no." },
      { slug: "wheel-of-names", name: "Wheel of Names", description: "Spin a wheel of your own names." },
      { slug: "coin-flip", name: "Coin Flip", description: "Flip a virtual coin." },
      { slug: "dice-roll", name: "Dice Roller", description: "Roll 1, 2 or 3 dice." },
    ],
  },
  {
    slug: "local-business",
    name: "Local Business",
    short: "Local",
    emoji: "\u{1F9F0}",
    description: "Quotes, invoices, estimates and everyday trade tools.",
    status: "soon",
    tools: [
      { slug: "invoice-generator", name: "Invoice Generator", description: "Make a printable invoice." },
      { slug: "sales-tax-calculator", name: "Sales Tax Calculator", description: "Add or remove sales tax." },
      { slug: "quote-calculator", name: "Quote Calculator", description: "Build a customer quote." },
      { slug: "receipt-generator", name: "Receipt Generator", description: "Simple printable receipts." },
      { slug: "estimate-template", name: "Estimate Template", description: "Quick job estimates." },
      { slug: "hourly-rate-calculator", name: "Hourly Rate Calculator", description: "Price your time." },
      { slug: "appointment-slot-generator", name: "Appointment Slots", description: "Build a booking grid." },
      { slug: "privacy-policy-generator", name: "Privacy Policy Generator", description: "A website privacy policy from a form." },
      { slug: "nda-generator", name: "NDA Generator", description: "A simple non-disclosure agreement." },
      { slug: "bill-of-sale", name: "Bill of Sale Generator", description: "A bill of sale for a private sale." },
    ],
  },
  {
    slug: "education",
    name: "Education & Productivity",
    short: "Education",
    emoji: "\u{1F393}",
    description: "GPA, reading time, citations and study tools.",
    status: "soon",
    tools: [
      { slug: "gpa-calculator", name: "GPA Calculator", description: "Grade point average." },
      { slug: "grade-calculator", name: "Grade Calculator", description: "Final grade you need." },
      { slug: "reading-time-calculator", name: "Reading Time Calculator", description: "Minutes to read text." },
      { slug: "citation-formatter", name: "Citation Formatter", description: "APA, MLA, Chicago." },
      { slug: "random-picker", name: "Random Picker", description: "Pick a name from a list." },
      { slug: "flashcard-generator", name: "Flashcard Generator", description: "Study cards from a list." },
      { slug: "study-planner", name: "Study Planner", description: "Plan revision sessions." },
    ],
  },
  {
    slug: "home-trade",
    name: "Home & Trade",
    short: "Home & Trade",
    emoji: "\u{1F3E0}",
    description: "Paint, concrete, flooring and other project calculators.",
    status: "soon",
    tools: [
      { slug: "concrete-calculator", name: "Concrete Calculator", description: "Volume of concrete." },
      { slug: "sheet-metal-gauge-converter", name: "Sheet Metal Gauge Converter", description: "Gauge to mm by metal type." },
      { slug: "pipe-size-converter", name: "Pipe Size Converter", description: "NPS, DN & actual OD." },
      { slug: "battery-equivalents", name: "Battery Cross-Reference", description: "Equivalent battery codes." },
      { slug: "bulb-base-converter", name: "Light Bulb Base Chart", description: "E26, E27, GU10, bayonet." },
      { slug: "firewood-calculator", name: "Firewood Cord Calculator", description: "Cords & face cords from a stack." },
      { slug: "paint-calculator", name: "Paint Calculator", description: "Litres of paint needed." },
      { slug: "flooring-calculator", name: "Flooring Calculator", description: "Boxes of flooring needed." },
      { slug: "tile-calculator", name: "Tile Calculator", description: "Tiles for an area." },
      { slug: "fence-calculator", name: "Fence Calculator", description: "Posts and panels needed." },
      { slug: "wallpaper-calculator", name: "Wallpaper Calculator", description: "Rolls of wallpaper." },
      { slug: "mulch-calculator", name: "Mulch & Soil Calculator", description: "Bags of mulch or soil." },
      { slug: "hvac-load-estimator", name: "HVAC Load Estimator", description: "Rough heating/cooling load." },
    ],
  },
  {
    slug: "audio-video",
    name: "Audio & Video",
    short: "Audio/Video",
    emoji: "\u{1F3AC}",
    description: "Convert, compress, trim, mute and extract — all in your browser.",
    status: "live",
    tools: [
      { slug: "video-converter", name: "Video Converter", description: "Convert between MP4, WEBM, MOV, MKV and AVI.", popular: true },
      { slug: "compress-video", name: "Compress Video", description: "Shrink a video's file size.", popular: true },
      { slug: "video-to-gif", name: "Video to GIF", description: "Turn a video clip into an animated GIF." },
      { slug: "resize-video", name: "Resize Video", description: "Change a video's resolution — 1080p to 360p." },
      { slug: "video-to-webp", name: "Video to WebP", description: "Turn a video clip into an animated WebP." },
      { slug: "add-subtitles", name: "Add Subtitles to Video", description: "Burn in or attach an .srt subtitle file." },
      { slug: "video-to-text", name: "Video & Audio to Text", description: "Transcribe speech to text and subtitles." },
      { slug: "audio-converter", name: "Audio Converter", description: "Convert audio to MP3, WAV, M4A, OGG or FLAC." },
      { slug: "video-to-audio", name: "Video to Audio (MP3)", description: "Extract the soundtrack from a video as MP3." },
      { slug: "mute-video", name: "Mute Video", description: "Remove the audio from a video." },
      { slug: "video-trim", name: "Trim Video", description: "Cut a clip from a video by start and end." },
      { slug: "audio-trim", name: "Trim Audio", description: "Cut a section out of an audio file." },
      { slug: "audio-merge", name: "Merge Audio", description: "Join several audio files into one." },
      { slug: "video-merge", name: "Merge Video", description: "Join several video clips into one." },
    ],
  },
];

// Site-wide category order: these pinned first (in this order), then every other
// category in its natural order above. Used by the menu, homepage tiles and footer.
const MENU_ORDER = ["games", "party", "pdf", "converters", "data"];
export const categories = rawCategories
  .map((c, i) => [c, i])
  .sort(([a, ai], [b, bi]) => {
    const rank = (slug) => MENU_ORDER.indexOf(slug) + 1 || MENU_ORDER.length + 1;
    return rank(a.slug) - rank(b.slug) || ai - bi;
  })
  .map(([c]) => c);

export function getCategory(slug) {
  return categories.find((c) => c.slug === slug) || null;
}

// Find a tool anywhere in the catalog by slug — used to build cross-category
// "related tools" links. Returns { tool, category } or null.
export function getToolBySlug(slug) {
  for (const c of categories) {
    const t = c.tools.find((x) => x.slug === slug);
    if (t) return { tool: t, category: c };
  }
  return null;
}

export function getTool(categorySlug, toolSlug) {
  const category = getCategory(categorySlug);
  if (!category) return null;
  return category.tools.find((t) => t.slug === toolSlug) || null;
}

// Flat list of every tool, tagged with its category — used by search.
export function allTools() {
  const out = [];
  for (const c of categories) {
    for (const t of c.tools) {
      out.push({
        ...t,
        category: c.slug,
        categoryName: c.name,
        emoji: c.emoji,
        href: `/${c.slug}/${t.slug}`,
      });
    }
  }
  return out;
}
