// The entire site's content lives here. Add categories and tools by editing this file.
// Tools within each category are ordered by demand (highest first). Paid/API tools
// (see COST notes) are placed LAST in their category so they land in the final build rounds.
// "Round N" of the launch plan = the Nth tool in each category.
// status: "live" | "soon".  tool.built: true once the tool actually works (until then its
// page is a "coming soon" stub, set to noindex).

// Canonical origin for the whole site (metadataBase, canonicals, og:url, sitemap, robots).
// Override with NEXT_PUBLIC_SITE_URL in Vercel if the custom domain isn't live yet,
// e.g. NEXT_PUBLIC_SITE_URL=https://everyboringtool.vercel.app
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://everyboringtool.com").replace(/\/+$/, "");

export const SITE = {
  name: "Every Boring Tool",
  short: "EBT",
  domain: SITE_URL.replace(/^https?:\/\//, ""),
  url: SITE_URL,
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL || "contact@everyboringtool.com",
  tagline: "Everything simple and boring.",
  description:
    "Every boring tool you need, in one simple place. Free, fast, and no sign-up — everything runs right in your browser.",
};

// Honest site-wide "content last reviewed" date, used for schema.org dateModified
// on tool pages. Kept as a hand-set constant (NOT the deploy date) so we only
// claim freshness when the content was actually touched — bump this when tool
// copy/FAQs are meaningfully updated. A per-tool `updated` field in toolContent
// overrides it where a single tool is revised on its own.
export const LAST_UPDATED = "2026-08-26";

// Categories are defined below in their natural grouping. The exported
// `categories` is a reordered view (see MENU_ORDER after the array) so the whole
// site — top menu, homepage tiles and footer — shows the same custom order.
const rawCategories = [
  {
    slug: "party",
    name: "Party Games",
    short: "Party Games",
    emoji: "\u{1F389}",
    description: "Team pickers, party-game generators, icebreakers and more.",
    tools: [
      { slug: "team-generator", name: "Team Generator", description: "Split names into random teams.", popular: true },
      { slug: "truth-or-dare", name: "Truth or Dare Generator", short: "Truth or Dare", description: "Random truths and dares." },
      { slug: "would-you-rather", name: "Would You Rather Generator", short: "Would You Rather", description: "Random would-you-rather dilemmas." },
      { slug: "never-have-i-ever", name: "Never Have I Ever Generator", short: "Never Have I Ever", description: "Random statements to play." },
      { slug: "charades-generator", name: "Charades Word Generator", short: "Charades", description: "Random words and phrases to act out." },
      { slug: "bingo-card-generator", name: "Bingo Card Generator", short: "Bingo Cards", description: "Printable bingo cards, numbers or words." },
      { slug: "pictionary-generator", name: "Pictionary Word Generator", short: "Pictionary", description: "Random words to draw." },
      { slug: "trivia-generator", name: "Trivia Question Generator", short: "Trivia", description: "Random trivia questions by category." },
      { slug: "spin-the-bottle", name: "Spin the Bottle", description: "An animated spinner for the classic game." },
      { slug: "team-name-generator", name: "Team Name Generator", short: "Team Names", description: "Random funny team names." },
      { slug: "secret-santa-generator", name: "Secret Santa Generator", short: "Secret Santa", description: "Draw names for a gift exchange." },
      { slug: "most-likely-to", name: "Who's Most Likely To Generator", short: "Most Likely To", description: "Random party prompts." },
      { slug: "icebreaker-generator", name: "Icebreaker Question Generator", short: "Icebreakers", description: "Random conversation starters." },
      { slug: "mafia-role-assigner", name: "Mafia Role Assigner", short: "Mafia Roles", description: "Deal secret roles to players." },
      { slug: "scattergories-generator", name: "Scattergories Generator", short: "Scattergories", description: "Random letter and category list." },
      { slug: "heads-up-generator", name: "Heads Up Word Generator", short: "Heads Up", description: "Random words to guess out loud." },
      { slug: "group-scoreboard", name: "Group Scoreboard", description: "Track scores for players or teams." },
      { slug: "random-turn-order", name: "Random Turn Order", description: "Shuffle who goes first." },
    ],
  },
  {
    slug: "pdf",
    name: "PDF Tools",
    short: "PDF",
    emoji: "\u{1F4C4}",
    description: "Merge, split, compress and convert PDFs — right in your browser.",
    status: "live",
    tools: [
      { slug: "pdf-metadata-editor", name: "PDF Metadata Editor", description: "This tool reads a PDF's document properties — title, author, subject, keywords, " },
      { slug: "pdf-to-markdown", name: "PDF to Markdown Converter", description: "This tool reads the text embedded in a PDF and rebuilds it as Markdown" },
      { slug: "bates-numbering", name: "Bates Numbering PDF Tool", description: "Bates numbering stamps a unique, sequential identifier on every page of a docume" },
      { slug: "fill-pdf-form", name: "Fill PDF Form", description: "This tool opens a PDF that already contains interactive form fields (an AcroForm" },
      { slug: "resize-pdf", name: "Resize PDF", description: "This tool changes the page dimensions of a PDF" },
      { slug: "redact-pdf", name: "Redact PDF", description: "Redact PDF lets you permanently black out sensitive information — names, account" },
      { slug: "unlock-pdf", name: "Unlock PDF", description: "Unlock PDF removes the password and permission restrictions from a PDF so you ca" },
      { slug: "merge-pdf", name: "Merge PDF", description: "Combine several PDFs into one file.", popular: true },
      { slug: "compress-pdf", name: "Compress PDF", description: "Shrink PDF size without wrecking quality." },
      { slug: "split-pdf", name: "Split PDF", description: "Separate a PDF into pages or ranges." },
      { slug: "word-to-pdf", name: "Word to PDF", description: "Convert a Word document to a PDF.", popular: true },
      { slug: "pdf-to-jpg", name: "PDF to JPG", description: "Turn each PDF page into an image." },
      { slug: "jpg-to-pdf", name: "JPG to PDF", description: "Combine images into a single PDF." },
      { slug: "rotate-pdf", name: "Rotate PDF", description: "Turn pages the right way up and save." },
      { slug: "protect-pdf", name: "Protect PDF", description: "Add a password to keep a PDF private." },
      { slug: "reorder-pages", name: "Reorder Pages", description: "Drag pages into the order you want." },
      { slug: "add-page-numbers", name: "Add Page Numbers", description: "Insert page numbers into a PDF." },
      { slug: "watermark-pdf", name: "Watermark PDF", description: "Stamp text or a logo across pages." },
      { slug: "pdf-to-png", name: "PDF to PNG", description: "Turn each PDF page into a PNG image." },
      { slug: "pdf-to-text", name: "PDF to Text", description: "Extract the text from a PDF." },
      { slug: "delete-pdf-pages", name: "Delete PDF Pages", description: "Remove chosen pages from a PDF." },
      { slug: "extract-pdf-pages", name: "Extract PDF Pages", description: "Pull a page range into a new PDF." },
      { slug: "crop-pdf", name: "Crop PDF", description: "Trim the margins of every page." },
      { slug: "add-text-to-pdf", name: "Add Text to PDF", description: "Add a line of text to a page." },
      { slug: "esign-pdf", name: "Sign PDF", description: "Draw a signature and place it." },
      { slug: "create-pdf", name: "Create PDF", description: "Make a PDF from typed text." },
      { slug: "extract-pdf-images", name: "Extract Images from PDF", short: "Extract Images", description: "Pull embedded images out of a PDF." },
      { slug: "reverse-pdf-pages", name: "Reverse PDF Pages", description: "Flip a PDF's page order." },
    ],
  },
  {
    slug: "image",
    name: "Image Tools",
    short: "Image",
    emoji: "\u{1F5BC}\u{FE0F}",
    description: "Compress, resize, convert and crop images in seconds.",
    status: "soon",
    tools: [
      { slug: "svg-optimizer", name: "SVG Optimizer", description: "This SVG optimizer reduces the file size of SVG images by removing data that bro" },
      { slug: "image-steganography", name: "Image Steganography (Hide Text in Image)", description: "This tool hides text inside an image using LSB (least significant bit) steganography" },
      { slug: "color-blindness-simulator", name: "Color Blindness Simulator", description: "This color blindness simulator shows how an image, chart, or interface looks to " },
      { slug: "image-to-ascii", name: "Image to ASCII Art Converter", description: "This tool converts an image into ASCII art - a picture made entirely of text characters" },
      { slug: "tiff-to-png", name: "TIFF to PNG Converter", description: "Most web browsers can't open TIFF files directly, so this tool includes its own " },
      { slug: "bmp-to-png", name: "BMP to PNG Converter", description: "This tool converts BMP (bitmap) images into PNG files" },
      { slug: "circle-crop", name: "Circle Crop Image", description: "This tool crops any photo into a perfect circle and saves it as a PNG" },
      { slug: "overlay-images", name: "Overlay Images", description: "Overlay Images lets you stack one picture on top of another and composite them i" },
      { slug: "placeholder-image", name: "Placeholder Image Generator", description: "This placeholder image generator makes blank dummy images at any dimension for m" },
      { slug: "round-corners", name: "Round Image Corners", description: "This tool rounds the corners of an image and gives you back a PNG with transpare" },
      { slug: "gif-to-png", name: "GIF to PNG Converter", description: "This tool turns a GIF into PNG images entirely inside your browser" },
      { slug: "avif-to-jpg", name: "AVIF to JPG Converter", description: "AVIF is a modern, highly compressed image format, but plenty of apps, older devi" },
      { slug: "photo-collage", name: "Photo Collage Maker", description: "This photo collage maker arranges your pictures into a clean grid you can custom" },
      { slug: "avif-to-png", name: "AVIF to PNG Converter", description: "This tool converts AVIF images into lossless PNG files" },
      { slug: "png-to-ico", name: "PNG to ICO Converter", description: "This tool converts a PNG (or JPG/WebP) image into a Windows .ico file, the forma" },
      { slug: "photo-filters", name: "Photo Filters", description: "Photo Filters lets you drop in a picture and apply popular looks like Vivid, Bla" },
      { slug: "passport-photo", name: "Passport Photo Maker", description: "This passport photo maker crops and sizes a head-and-shoulders photo to the exac" },
      { slug: "heic-to-png", name: "HEIC to PNG Converter", description: "iPhones and iPads save photos in HEIC (High Efficiency Image Container, also wri" },
      { slug: "image-color-picker", name: "Image Color Picker", description: "This image color picker lets you upload any photo, screenshot, or graphic and re" },
      { slug: "image-compressor", name: "Image Compressor", description: "Shrink image file size.", popular: true },
      { slug: "pfp-maker", name: "PFP Maker", description: "Turn a photo into a clean profile picture.", popular: true },
      { slug: "image-resizer", name: "Image Resizer", description: "Resize to any dimensions." },
      { slug: "crop-image", name: "Crop Image", description: "Crop to a shape or ratio." },
      { slug: "png-to-jpg", name: "PNG to JPG", description: "Convert PNG images to JPG." },
      { slug: "jpg-to-png", name: "JPG to PNG", description: "Convert JPG images to PNG." },
      { slug: "image-to-webp", name: "Image to WebP", description: "Convert JPG/PNG to WebP." },
      { slug: "heic-to-jpg", name: "HEIC to JPG", description: "Convert iPhone HEIC photos." },
      { slug: "rotate-image", name: "Rotate Image", short: "Rotate & Flip", description: "Rotate or mirror an image." },
      { slug: "image-to-text", name: "Image to Text (OCR)", description: "Extract text from an image." },
      { slug: "webp-to-png", name: "WebP to PNG", description: "Convert WebP back to PNG." },
      { slug: "svg-to-png", name: "SVG to PNG", description: "Rasterize SVG to PNG." },
      { slug: "favicon-generator", name: "Favicon Generator", description: "Make a favicon from an image." },
      { slug: "image-to-base64", name: "Image to Base64", description: "Encode an image as text." },
      { slug: "meme-generator", name: "Meme Generator", description: "Add top/bottom text to images." },
      { slug: "black-and-white", name: "Black & White", description: "Turn a photo greyscale." },
      { slug: "sepia-image", name: "Sepia Photo", description: "Add a warm vintage tone." },
      { slug: "invert-colors", name: "Invert Image Colors", short: "Invert Colors", description: "Make a photo negative." },
      { slug: "brightness-contrast", name: "Brightness & Contrast", short: "Brightness/Contrast", description: "Adjust brightness and contrast." },
      { slug: "blur-image", name: "Blur Image", description: "Soften an image or hide detail." },
      { slug: "sharpen-image", name: "Sharpen Image", description: "Sharpen a soft or blurry photo." },
      { slug: "pixelate-image", name: "Pixelate Image", description: "Add a pixel or mosaic effect." },
      { slug: "add-border-to-image", name: "Add Border to Image", description: "Add a colored frame." },
      { slug: "add-text-to-image", name: "Add Text to Image", description: "Add a caption to an image." },
      { slug: "round-image", name: "Round Image", description: "Crop to a circle for a profile pic." },
      { slug: "webp-to-jpg", name: "WebP to JPG", description: "Convert a WebP image to JPG." },
      { slug: "combine-images", name: "Combine Images", description: "Merge images into one." },
      { slug: "collage-maker", name: "Collage Maker", description: "Arrange photos into a grid." },
      { slug: "image-splitter", name: "Image Splitter", description: "Split an image into a grid of tiles." },
      { slug: "exif-viewer", name: "EXIF Viewer", description: "See a photo's metadata and GPS." },
      { slug: "chart-maker", name: "Chart Maker", description: "Turn numbers into a bar chart image." },
      { slug: "white-screen", name: "White Screen", description: "Full-screen white or colour test screen." },
    ],
  },
  {
    slug: "calculators",
    name: "Calculators",
    short: "Calculators",
    emoji: "\u{1F522}",
    description: "Percentages, BMI, tips, discounts — quick everyday answers.",
    status: "soon",
    tools: [
      { slug: "aspect-ratio-calculator", name: "Aspect Ratio Calculator", description: "This aspect ratio calculator does two jobs" },
      { slug: "ideal-weight-calculator", name: "Ideal Weight Calculator", description: "This ideal weight calculator estimates a target body weight from your height and" },
      { slug: "body-fat-calculator", name: "Body Fat Calculator", description: "This body fat calculator estimates your body fat percentage from a few tape-meas" },
      { slug: "fuel-cost-calculator", name: "Fuel Cost Calculator", description: "This fuel cost calculator estimates what a drive will cost in gas or diesel" },
      { slug: "percentage-calculator", name: "Percentage Calculator", short: "Percentage", description: "Work out any percentage." },
      { slug: "bmi-calculator", name: "BMI Calculator", description: "Body mass index." },
      { slug: "tip-calculator", name: "Tip Calculator", description: "Split the bill and tip." },
      { slug: "discount-calculator", name: "Discount Calculator", description: "Price after a discount." },
      { slug: "average-calculator", name: "Average Calculator", description: "Mean, median and mode." },
      { slug: "scientific-calculator", name: "Scientific Calculator", short: "Scientific", description: "Full scientific calculator." },
      { slug: "random-number-generator", name: "Random Number Generator", short: "Random Number", description: "Pick random numbers." },
      { slug: "ratio-calculator", name: "Ratio Calculator", description: "Solve and scale ratios." },
      { slug: "fraction-calculator", name: "Fraction Calculator", description: "Add and simplify fractions." },
      { slug: "calorie-calculator", name: "Calorie Calculator", description: "Daily calorie needs." },
      { slug: "perfume-split-calculator", name: "Perfume Split Calculator", short: "Perfume Split", description: "Split a bottle's cost by ml." },
    ],
  },
  {
    slug: "text",
    name: "Text & Writing",
    short: "Text",
    emoji: "\u{270D}\u{FE0F}",
    description: "Counters, case converters, unscramblers and text cleanup.",
    status: "soon",
    tools: [
      { slug: "word-frequency-counter", name: "Word Frequency Counter", description: "Word Frequency Counter tallies how many times every word appears in the text you" },
      { slug: "remove-line-breaks", name: "Remove Line Breaks From Text", description: "This tool strips the hard line breaks out of pasted text" },
      { slug: "text-repeater", name: "Text Repeater", description: "The Text Repeater takes whatever you type and duplicates it as many times as you ask for" },
      { slug: "reverse-text", name: "Reverse Text", description: "Reverse Text flips your writing several ways from one box" },
      { slug: "word-counter", name: "Word Counter", description: "Count words and characters.", popular: true },
      { slug: "grammar-checker", name: "Grammar & Spell Checker", short: "Grammar Check", description: "Check spelling and grammar, locally.", popular: true },
      { slug: "character-counter", name: "Character Counter", description: "Count characters with limits." },
      { slug: "case-converter", name: "Case Converter", description: "UPPER, lower, Title, Sentence." },
      { slug: "fancy-font-generator", name: "Fancy Text Generator", short: "Fancy Text", description: "Bold/italic unicode text." },
      { slug: "lorem-ipsum-generator", name: "Lorem Ipsum Generator", short: "Lorem Ipsum", description: "Generate placeholder text." },
      { slug: "text-diff", name: "Text Diff Checker", description: "Compare two blocks of text." },
      { slug: "find-and-replace", name: "Find & Replace", description: "Bulk find and replace text." },
      { slug: "sort-lines", name: "Sort Lines", description: "Sort lines alphabetically." },
      { slug: "remove-duplicate-lines", name: "Remove Duplicate Lines", short: "Remove Duplicates", description: "Delete repeated lines." },
      { slug: "slugify", name: "Slug Generator", description: "Make URL-friendly slugs." },
      { slug: "text-reverser", name: "Text Reverser", description: "Reverse text or words." },
      { slug: "morse-code-translator", name: "Morse Code Translator", short: "Morse Code", description: "Text to and from Morse." },
      { slug: "genz-translator", name: "Gen Z Slang Translator", short: "Gen Z Slang", description: "Gen Z slang to plain English & back." },
      { slug: "html-to-text", name: "HTML to Text", description: "Strip tags to plain text." },
    ],
  },
  {
    slug: "converters",
    name: "Converters",
    short: "Converters",
    emoji: "\u{1F504}",
    description: "Units, colors, bases, data formats and currency.",
    status: "soon",
    tools: [
      { slug: "unit-converter", name: "Unit Converter", description: "Convert any common unit." },
      { slug: "currency-converter", name: "Currency Converter", short: "Currency", description: "Live rates for 30+ currencies." },
      { slug: "length-converter", name: "Length Converter", description: "Metric and imperial length." },
      { slug: "temperature-converter", name: "Temperature Converter", short: "Temperature", description: "Celsius, Fahrenheit, Kelvin." },
      { slug: "weight-converter", name: "Weight Converter", description: "Kg, lb, oz and more." },
      { slug: "color-converter", name: "Color Converter", description: "HEX, RGB and HSL." },
      { slug: "number-base-converter", name: "Base Converter", description: "Binary, hex, decimal, octal." },
      { slug: "roman-numeral-converter", name: "Roman Numeral Converter", short: "Roman Numerals", description: "Numbers to Roman numerals." },
      { slug: "number-to-words", name: "Number to Words", description: "Spell out any number." },
      { slug: "clothing-size-converter", name: "Clothing Size Converter", short: "Clothing Sizes", description: "US, UK, EU sizes by country." },
      { slug: "ring-size-converter", name: "Ring Size Converter", description: "US, UK, EU, Japan & mm." },
      { slug: "bra-size-converter", name: "Bra Size Calculator & Converter", short: "Bra Size Calculator", description: "Measure your size, or convert US, UK, EU, FR, AU." },
      { slug: "drill-bit-size-converter", name: "Drill Bit Size Converter", short: "Drill Bit Sizes", description: "Fraction, metric, letter, number." },
      { slug: "knitting-crochet-converter", name: "Knitting & Crochet Sizes", short: "Knitting/Crochet", description: "Needle & hook: US, UK, mm." },
      { slug: "cups-to-grams-converter", name: "Cups to Grams Converter", short: "Cups to Grams", description: "By ingredient — flour, sugar, etc." },
      { slug: "oven-temperature-converter", name: "Oven Temperature Converter", short: "Oven Temperature", description: "°F, °C, gas mark & fan." },
      { slug: "pan-size-converter", name: "Cake Pan Size Converter", short: "Cake Pan Sizes", description: "Swap round, square & rectangular tins." },
      { slug: "yeast-converter", name: "Yeast Converter", description: "Active dry, instant & fresh yeast." },
      { slug: "paper-size-converter", name: "Paper Size Converter", short: "Paper Sizes", description: "A4, Letter, B & C series." },
      { slug: "kids-clothing-size-converter", name: "Kids Clothing Size Converter", short: "Kids Clothing Sizes", description: "Baby & kids US, UK, EU." },
      { slug: "thread-size-converter", name: "Thread Size Converter", short: "Thread Sizes", description: "Tex, denier, Nm, ticket." },
      { slug: "bead-size-converter", name: "Bead Size Converter", description: "Seed bead aught to mm." },
    ],
  },
  {
    slug: "data",
    name: "Data",
    short: "Data",
    emoji: "\u{1F5C3}\u{FE0F}",
    description: "Convert between CSV, JSON, XML, YAML, Excel and more — data & file formats.",
    status: "live",
    tools: [
      { slug: "csv-to-json", name: "CSV to JSON", description: "Convert CSV into JSON." },
      { slug: "json-to-csv", name: "JSON to CSV", description: "Convert JSON into CSV." },
      { slug: "markdown-to-html", name: "Markdown to HTML", description: "Render Markdown as HTML." },
      { slug: "xml-to-json", name: "XML to JSON", description: "Convert XML into JSON." },
      { slug: "json-to-xml", name: "JSON to XML", description: "Convert JSON into XML." },
      { slug: "xml-to-csv", name: "XML to CSV", description: "Turn XML records into CSV." },
      { slug: "csv-to-xml", name: "CSV to XML", description: "Turn CSV rows into XML." },
      { slug: "csv-to-markdown", name: "CSV to Markdown", description: "CSV into a Markdown table." },
      { slug: "csv-to-html", name: "CSV to HTML Table", description: "CSV into an HTML table." },
      { slug: "html-table-to-csv", name: "HTML Table to CSV", description: "Pull a table out of HTML as CSV." },
      { slug: "csv-to-excel", name: "CSV to Excel", description: "CSV into an .xlsx spreadsheet." },
      { slug: "excel-to-csv", name: "Excel to CSV", description: "An .xlsx or .xls into CSV." },
      { slug: "excel-to-json", name: "Excel to JSON", description: "A spreadsheet into JSON." },
      { slug: "json-to-excel", name: "JSON to Excel", description: "JSON into an .xlsx spreadsheet." },
      { slug: "excel-to-html", name: "Excel to HTML Table", description: "A spreadsheet into an HTML table." },
      { slug: "split-csv", name: "Split CSV", description: "Split a big CSV into smaller files." },
      { slug: "tsv-to-csv", name: "TSV to CSV", description: "Tab-separated into comma-separated." },
      { slug: "csv-to-tsv", name: "CSV to TSV", description: "Comma-separated into tab-separated." },
      { slug: "yaml-to-json", name: "YAML to JSON", description: "Convert YAML into JSON." },
      { slug: "json-to-yaml", name: "JSON to YAML", description: "Convert JSON into YAML." },
    ],
  },
  {
    slug: "qr-barcode",
    name: "QR & Barcode",
    short: "QR",
    emoji: "\u{1F533}",
    description: "Generate and scan QR codes and barcodes of every kind.",
    status: "soon",
    tools: [
      { slug: "qr-code-generator", name: "QR Code Generator", description: "Make a QR code for anything.", popular: true },
      { slug: "wifi-qr-generator", name: "Wi-Fi QR Generator", description: "Share Wi-Fi with a scan." },
      { slug: "qr-code-scanner", name: "QR Code Scanner", description: "Scan a QR from a photo." },
      { slug: "url-qr-generator", name: "URL QR Generator", description: "QR for any link." },
      { slug: "vcard-qr-generator", name: "vCard QR Generator", description: "A QR contact card." },
      { slug: "whatsapp-qr-generator", name: "WhatsApp QR Generator", short: "WhatsApp QR", description: "QR to a WhatsApp chat." },
      { slug: "barcode-generator", name: "Barcode Generator", description: "Create common barcodes." },
      { slug: "email-qr-generator", name: "Email QR Generator", description: "QR that opens an email." },
    ],
  },
  {
    slug: "datetime",
    name: "Date & Time",
    short: "Date & Time",
    emoji: "\u{23F1}\u{FE0F}",
    description: "Ages, date maths, countdowns, timers and time zones.",
    status: "soon",
    tools: [
      { slug: "due-date-calculator", name: "Due Date Calculator", description: "This due date calculator estimates when your baby is likely to arrive and shows " },
      { slug: "timezone-converter", name: "Timezone Converter", description: "This timezone converter turns a date and time from one place into the matching l" },
      { slug: "age-calculator", name: "Age Calculator", description: "Age from a birth date.", popular: true },
      { slug: "countdown-timer", name: "Countdown Timer", description: "Count down to a date." },
      { slug: "date-difference", name: "Date Difference", description: "Days between two dates." },
      { slug: "pomodoro-timer", name: "Pomodoro Timer", description: "Focus in 25-minute blocks." },
      { slug: "stopwatch", name: "Stopwatch", description: "Simple online stopwatch." },
      { slug: "business-days-calculator", name: "Business Days Calculator", short: "Business Days", description: "Working days between dates." },
      { slug: "work-hours-calculator", name: "Work Hours Calculator", short: "Work Hours", description: "Hours from a timesheet." },
      { slug: "week-number", name: "Week Number Calculator", short: "Week Number", description: "Find the current week number." },
      { slug: "add-subtract-days", name: "Add or Subtract Days", short: "Add/Subtract Days", description: "Shift a date by N days." },
      { slug: "time-zone-converter", name: "Live Clock & Time Zone Converter", short: "Clock & Time Zones", description: "Live local clock, plus convert times worldwide." },
    ],
  },
  {
    slug: "finance",
    name: "Finance",
    short: "Finance",
    emoji: "\u{1F4B0}",
    description: "Loan, mortgage, interest, tax and investment calculators.",
    status: "soon",
    tools: [
      { slug: "burn-rate-calculator", name: "Burn Rate Calculator", description: "A burn rate calculator shows how fast your company is spending cash and how long" },
      { slug: "black-scholes-calculator", name: "Black-Scholes Calculator", description: "This calculator prices European-style call and put options using the Black-Schol" },
      { slug: "position-size-calculator", name: "Position Size Calculator", description: "A position size calculator tells you how many shares, units, or lots to buy so t" },
      { slug: "kelly-criterion-calculator", name: "Kelly Criterion Calculator", description: "The Kelly Criterion is a formula for sizing bets or investments to maximize the " },
      { slug: "cash-flow-calculator", name: "Cash Flow Calculator", description: "This cash flow calculator adds up your monthly income and expenses to show your " },
      { slug: "forex-pip-calculator", name: "Forex Pip Calculator", description: "This forex pip calculator works out how much one pip is worth for a given curren" },
      { slug: "bond-ytm-calculator", name: "Bond Yield to Maturity Calculator", description: "This calculator finds a bond's yield to maturity (YTM): the single annual rate t" },
      { slug: "stock-average-calculator", name: "Stock Average Calculator", description: "A stock average calculator works out your average cost per share when you have b" },
      { slug: "crypto-profit-calculator", name: "Crypto Profit Calculator", description: "This crypto profit calculator works out the profit or loss on a trade from your " },
      { slug: "dividend-calculator", name: "Dividend Calculator", description: "This dividend calculator projects how a dividend-paying holding grows over time" },
      { slug: "cagr-calculator", name: "CAGR Calculator", description: "This CAGR calculator finds the compound annual growth rate of an investment or a" },
      { slug: "fire-calculator", name: "FIRE Calculator (Financial Independence)", description: "This FIRE (Financial Independence, Retire Early) calculator estimates two things" },
      { slug: "take-home-pay-calculator", name: "Take-Home Pay Calculator", description: "This take-home pay calculator estimates your net paycheck after taxes and common" },
      { slug: "loan-calculator", name: "Loan / EMI Calculator", short: "Loan / EMI", description: "Monthly loan payments." },
      { slug: "mortgage-calculator", name: "Mortgage Calculator", description: "Home loan repayments." },
      { slug: "compound-interest-calculator", name: "Compound Interest Calculator", short: "Compound Interest", description: "Growth over time." },
      { slug: "salary-calculator", name: "Salary Calculator", description: "Hourly to annual pay." },
      { slug: "sip-calculator", name: "SIP Calculator", description: "Systematic investment returns." },
      { slug: "gst-vat-calculator", name: "GST / VAT Calculator", short: "GST / VAT", description: "Add or remove tax." },
      { slug: "simple-interest-calculator", name: "Simple Interest Calculator", description: "Flat interest maths." },
      { slug: "roi-calculator", name: "ROI Calculator", description: "Return on investment." },
      { slug: "inflation-calculator", name: "Inflation Calculator", short: "Inflation", description: "Value of money over time." },
      { slug: "savings-goal-calculator", name: "Savings Goal Calculator", short: "Savings Goal", description: "Reach a savings target." },
    ],
  },
  {
    slug: "developer",
    name: "Developer",
    short: "Developer",
    emoji: "\u{1F468}\u{200D}\u{1F4BB}",
    description: "JSON, regex, hashes, encoders, formatters and generators.",
    status: "soon",
    tools: [
      { slug: "css-formatter", name: "CSS Formatter & Beautifier", description: "This free CSS formatter cleans up messy or minified stylesheets in one step" },
      { slug: "json-schema-generator", name: "JSON Schema Generator", description: "This JSON Schema Generator turns a sample JSON object or array into a valid JSON Schema" },
      { slug: "px-to-rem-converter", name: "PX to REM Converter", description: "This PX to REM Converter turns pixel values into rem units and back again for CSS" },
      { slug: "unicode-lookup", name: "Unicode Character Lookup", description: "Paste text to break it into individual code points, or enter a code point (U+1F6" },
      { slug: "bitwise-calculator", name: "Bitwise Calculator", description: "This bitwise calculator performs the core boolean and shift operations programme" },
      { slug: "user-agent-parser", name: "User Agent Parser", description: "This User Agent parser breaks a raw User-Agent string down into its parts: the b" },
      { slug: "jsonpath-tester", name: "JSONPath Tester", description: "Paste a JSON document, type a JSONPath expression, and this tester shows the mat" },
      { slug: "password-strength-checker", name: "Password Strength Checker", description: "This password strength checker estimates how hard your password would be to gues" },
      { slug: "csv-viewer", name: "CSV Viewer", description: "This CSV viewer turns a comma-separated file into a readable table you can sort and search" },
      { slug: "chmod-calculator", name: "Chmod Calculator", description: "This chmod calculator turns Unix and Linux file permissions into the numbers and" },
      { slug: "javascript-formatter", name: "JavaScript Formatter & Beautifier", description: "Paste minified, compressed, or poorly indented JavaScript and this tool re-inden" },
      { slug: "markdown-table-generator", name: "Markdown Table Generator", description: "This Markdown Table Generator turns a simple spreadsheet-style grid into clean G" },
      { slug: "json-escape", name: "JSON Escape / Unescape", description: "This tool converts between raw text and JSON-escaped strings" },
      { slug: "browser-fingerprint", name: "Browser Fingerprint Test", description: "This browser fingerprint test reads the signals your browser exposes to any webs" },
      { slug: "file-encryptor", name: "File Encryptor — Encrypt File Online", description: "This tool password-protects any file with strong, industry-standard encryption" },
      { slug: "box-shadow-generator", name: "CSS Box Shadow Generator", description: "This is a visual CSS box-shadow generator" },
      { slug: "random-string-generator", name: "Random String Generator", description: "This tool generates random strings using your browser's built-in cryptographical" },
      { slug: "binary-text-converter", name: "Binary to Text Converter", description: "This tool converts binary code to readable text and text back into binary" },
      { slug: "markdown-preview", name: "Markdown Preview Editor", description: "This is a live Markdown editor and previewer" },
      { slug: "color-contrast-checker", name: "Color Contrast Checker (WCAG)", description: "This color contrast checker measures the WCAG 2.x contrast ratio between a foreg" },
      { slug: "sql-formatter", name: "SQL Formatter", description: "This SQL formatter takes a cramped, one-line, or inconsistently spaced query and" },
      { slug: "http-status-codes", name: "HTTP Status Codes Reference", description: "This is a fast, searchable reference for HTTP response status codes" },
      { slug: "html-formatter", name: "HTML Formatter & Beautifier", description: "This HTML formatter takes messy, minified, or hand-written HTML and re-indents i" },
      { slug: "json-diff", name: "JSON Diff Compare", description: "JSON Diff Compare takes two JSON documents and shows you exactly how they differ" },
      { slug: "timestamp-converter", name: "Unix Timestamp Converter", description: "This tool converts between Unix timestamps and human-readable dates in both directions" },
      { slug: "xml-formatter", name: "XML Formatter", description: "Paste raw or one-line XML and this tool re-indents it into clean, readable marku" },
      { slug: "url-encoder", name: "URL Encoder / Decoder", description: "This tool percent-encodes and decodes URLs so special characters travel safely i" },
      { slug: "caesar-cipher", name: "Caesar Cipher Encoder & Decoder", description: "A Caesar cipher shifts every letter in your message forward or backward by a fix" },
      { slug: "subnet-calculator", name: "Subnet Calculator (IPv4 CIDR)", description: "This subnet calculator takes an IPv4 address and a CIDR prefix (/0 to /32) and w" },
      { slug: "json-formatter", name: "JSON Formatter", description: "Format, repair and validate JSON.", popular: true },
      { slug: "base64-encode-decode", name: "Base64 Encode / Decode", short: "Base64 Encode/Decode", description: "Convert to and from Base64." },
      { slug: "password-generator", name: "Password Generator", description: "Strong random passwords." },
      { slug: "hash-generator", name: "Hash Generator", description: "MD5, SHA-1, SHA-256." },
      { slug: "url-encode-decode", name: "URL Encode / Decode", description: "Escape and unescape URLs." },
      { slug: "uuid-generator", name: "UUID Generator", description: "Generate unique IDs." },
      { slug: "regex-tester", name: "Regex Tester", description: "Test regular expressions." },
      { slug: "jwt-decoder", name: "JWT Decoder", description: "Decode a JSON web token." },
      { slug: "color-picker", name: "Color Picker", description: "Pick and copy colors." },
      { slug: "html-minifier", name: "HTML Minifier", description: "Shrink HTML markup." },
      { slug: "css-minifier", name: "CSS Minifier", description: "Shrink CSS files." },
      { slug: "js-minifier", name: "JS Minifier", description: "Shrink JavaScript." },
      { slug: "cron-generator", name: "Cron Generator", description: "Build cron expressions." },
      { slug: "json-minify", name: "JSON Minify & Beautify", short: "JSON Minify", description: "Minify or beautify JSON." },
      { slug: "epoch-converter", name: "Epoch Converter", description: "Unix timestamp to date and back." },
      { slug: "url-parser", name: "URL Parser", description: "Break a URL into its parts." },
      { slug: "create-zip", name: "Create ZIP File", description: "Bundle files into a .zip archive." },
    ],
  },
  {
    slug: "seo-web",
    name: "SEO & Web",
    short: "SEO",
    emoji: "\u{1F4C8}",
    description: "Meta tags, schema, sitemaps and search-preview tools.",
    status: "soon",
    tools: [
      { slug: "readability-checker", name: "Readability Score Checker", description: "Paste or type any text and this tool scores how easy it is to read" },
      { slug: "sitemap-generator", name: "XML Sitemap Generator", description: "This tool turns a plain list of page URLs into a valid XML sitemap that follows " },
      { slug: "meta-tag-generator", name: "Meta Tag Generator", description: "Build SEO meta tags." },
      { slug: "keyword-density-checker", name: "Keyword Density Checker", short: "Keyword Density", description: "Analyze keyword usage." },
      { slug: "serp-snippet-preview", name: "SERP Snippet Preview", short: "SERP Preview", description: "Preview a Google result." },
      { slug: "schema-generator", name: "Schema Generator", description: "JSON-LD structured data." },
      { slug: "robots-txt-generator", name: "Robots.txt Generator", short: "Robots.txt", description: "Create a robots.txt file." },
      { slug: "slug-generator", name: "URL Slug Generator", description: "SEO-friendly URL slugs." },
      { slug: "canonical-tag-generator", name: "Canonical Tag Generator", short: "Canonical Tags", description: "Build canonical tags." },
      { slug: "llms-txt-generator", name: "llms.txt Generator", description: "Guide AI crawlers." },
    ],
  },
  {
    slug: "marketing",
    name: "Marketing & Business",
    short: "Marketing",
    emoji: "\u{1F4E3}",
    description: "Margins, ROAS, break-even and campaign tools.",
    status: "soon",
    tools: [
      { slug: "ltv-calculator", name: "LTV Calculator (Customer Lifetime Value)", description: "This calculator estimates customer lifetime value (LTV), the total profit you ca" },
      { slug: "profit-margin-calculator", name: "Profit Margin Calculator", short: "Profit Margin", description: "Margin and profit." },
      { slug: "roas-calculator", name: "ROAS Calculator", description: "Return on ad spend." },
      { slug: "markup-calculator", name: "Markup Calculator", description: "Price from cost + markup." },
      { slug: "break-even-calculator", name: "Break-even Calculator", short: "Break-even", description: "Units to break even." },
      { slug: "conversion-rate-calculator", name: "Conversion Rate Calculator", short: "Conversion Rate", description: "Conversions ÷ visitors." },
      { slug: "cpm-calculator", name: "CPM Calculator", description: "Cost per thousand impressions." },
      { slug: "cac-calculator", name: "CAC Calculator", description: "Customer acquisition cost." },
      { slug: "cpa-calculator", name: "CPA Calculator", description: "Cost per acquisition." },
      { slug: "utm-builder", name: "UTM Builder", description: "Tag campaign links." },
      { slug: "landing-page-roi-calculator", name: "Landing Page ROI", description: "Traffic to revenue." },
      { slug: "email-subject-line-tester", name: "Subject Line Tester", description: "Score an email subject." },
    ],
  },
  {
    slug: "social",
    name: "Social Media",
    short: "Social",
    emoji: "\u{1F4F1}",
    description: "Resizers, hashtags, captions and creator utilities.",
    status: "soon",
    tools: [
      { slug: "instagram-image-resizer", name: "Instagram Image Resizer", short: "Instagram Resizer", description: "Perfect post/story sizes." },
      { slug: "hashtag-generator", name: "Hashtag Generator", description: "Relevant hashtags fast." },
      { slug: "tweet-character-counter", name: "Tweet Character Counter", short: "Tweet Characters", description: "Count against the limit." },
      { slug: "bio-character-counter", name: "Bio Character Counter", short: "Bio Characters", description: "Fit platform bio limits." },
      { slug: "caption-formatter", name: "Caption Formatter", description: "Add line breaks for IG." },
      { slug: "youtube-thumbnail-resizer", name: "YouTube Thumbnail Resizer", short: "YouTube Thumbnail", description: "Resize to 1280×720." },
      { slug: "engagement-rate-calculator", name: "Engagement Rate Calculator", short: "Engagement Rate", description: "Rate from likes/followers." },
      { slug: "link-in-bio-qr", name: "Link-in-Bio QR", description: "QR to your bio link." },
    ],
  },
  {
    slug: "ecommerce",
    name: "E-commerce",
    short: "E-commerce",
    emoji: "\u{1F6D2}",
    description: "Seller fee, margin and pricing calculators.",
    status: "soon",
    tools: [
      { slug: "amazon-margin-calculator", name: "Amazon Margin Calculator", short: "Amazon Margin", description: "FBA fees and margin." },
      { slug: "shopify-fee-calculator", name: "Shopify Fee Calculator", short: "Shopify Fees", description: "Fees and net payout." },
      { slug: "etsy-fee-calculator", name: "Etsy Fee Calculator", description: "Listing and payment fees." },
      { slug: "price-after-fees-calculator", name: "Price After Fees", description: "What you actually keep." },
      { slug: "dropshipping-profit-calculator", name: "Dropshipping Profit", description: "Profit per order." },
      { slug: "sku-generator", name: "SKU Generator", description: "Structured product SKUs." },
      { slug: "product-title-counter", name: "Product Title Counter", short: "Title Characters", description: "Fit marketplace limits." },
    ],
  },
  {
    slug: "games",
    name: "Games",
    short: "Games",
    emoji: "\u{1F3AE}",
    description: "Sudoku, typing tests, word games and quick classics.",
    status: "soon",
    tools: [
      { slug: "sudoku", name: "Sudoku", description: "Classic number puzzle." },
      { slug: "typing-speed-test", name: "Typing Test", short: "Typing Test", description: "Timed WPM & accuracy test." },
      { slug: "2048", name: "2048", description: "Slide tiles to 2048." },
      { slug: "wordle", name: "Wordle", description: "Guess the daily word." },
      { slug: "minesweeper", name: "Minesweeper", description: "The classic mine puzzle." },
      { slug: "solitaire", name: "Solitaire", description: "Klondike solitaire." },
      { slug: "reaction-time-test", name: "Reaction Time Test", description: "How fast are you?" },
      { slug: "cps-test", name: "Click Speed Test", description: "Clicks per second." },
      { slug: "hangman", name: "Hangman", description: "Guess the hidden word." },
      { slug: "word-search", name: "Word Search", description: "Find the hidden words." },
      { slug: "memory-match", name: "Memory Match", description: "Flip and match pairs." },
      { slug: "tic-tac-toe", name: "Tic-Tac-Toe", description: "Play vs an unbeatable AI." },
      { slug: "yes-no-wheel", name: "Yes or No Wheel", description: "Spin for a random yes or no." },
      { slug: "wheel-of-names", name: "Wheel of Names", description: "Spin a wheel of your own names." },
      { slug: "coin-flip", name: "Coin Flip", description: "Flip a virtual coin." },
      { slug: "dice-roll", name: "Dice Roller", description: "Roll 1, 2 or 3 dice." },
    ],
  },
  {
    slug: "local-business",
    name: "Local Business",
    short: "Local",
    emoji: "\u{1F9F0}",
    description: "Quotes, invoices, estimates and everyday trade tools.",
    status: "soon",
    tools: [
      { slug: "invoice-generator", name: "Invoice Generator", description: "Make a printable invoice." },
      { slug: "sales-tax-calculator", name: "Sales Tax Calculator", short: "Sales Tax", description: "Add or remove sales tax." },
      { slug: "quote-calculator", name: "Quote Calculator", description: "Build a customer quote." },
      { slug: "receipt-generator", name: "Receipt Generator", description: "Simple printable receipts." },
      { slug: "estimate-template", name: "Estimate Template", description: "Quick job estimates." },
      { slug: "hourly-rate-calculator", name: "Hourly Rate Calculator", short: "Hourly Rate", description: "Price your time." },
      { slug: "appointment-slot-generator", name: "Appointment Slots", description: "Build a booking grid." },
      { slug: "privacy-policy-generator", name: "Privacy Policy Generator", short: "Privacy Policy", description: "A website privacy policy from a form." },
      { slug: "nda-generator", name: "NDA Generator", description: "A simple non-disclosure agreement." },
      { slug: "bill-of-sale", name: "Bill of Sale Generator", short: "Bill of Sale", description: "A bill of sale for a private sale." },
    ],
  },
  {
    slug: "education",
    name: "Education & Productivity",
    short: "Education",
    emoji: "\u{1F393}",
    description: "GPA, reading time, citations and study tools.",
    status: "soon",
    tools: [
      { slug: "gpa-calculator", name: "GPA Calculator", description: "Grade point average." },
      { slug: "grade-calculator", name: "Grade Calculator", description: "Final grade you need." },
      { slug: "reading-time-calculator", name: "Reading Time Calculator", short: "Reading Time", description: "Minutes to read text." },
      { slug: "citation-formatter", name: "Citation Generator", description: "APA, MLA, Chicago." },
      { slug: "random-picker", name: "Random Name Picker", short: "Random Picker", description: "Pick a name from a list." },
      { slug: "flashcard-generator", name: "Flashcard Generator", description: "Study cards from a list." },
      { slug: "study-planner", name: "Study Planner", description: "Plan revision sessions." },
    ],
  },
  {
    slug: "home-trade",
    name: "Home & Trade",
    short: "Home & Trade",
    emoji: "\u{1F3E0}",
    description: "Paint, concrete, flooring and other project calculators.",
    status: "soon",
    tools: [
      { slug: "concrete-calculator", name: "Concrete Calculator", description: "Volume of concrete." },
      { slug: "sheet-metal-gauge-converter", name: "Sheet Metal Gauge Converter", short: "Sheet Metal Gauge", description: "Gauge to mm by metal type." },
      { slug: "pipe-size-converter", name: "Pipe Size Converter", description: "NPS, DN & actual OD." },
      { slug: "battery-equivalents", name: "Battery Cross-Reference", short: "Battery Equivalents", description: "Equivalent battery codes." },
      { slug: "bulb-base-converter", name: "Light Bulb Base Chart", short: "Bulb Base Chart", description: "E26, E27, GU10, bayonet." },
      { slug: "firewood-calculator", name: "Firewood Cord Calculator", short: "Firewood Cord", description: "Cords & face cords from a stack." },
      { slug: "paint-calculator", name: "Paint Calculator", description: "Litres of paint needed." },
      { slug: "flooring-calculator", name: "Flooring Calculator", description: "Boxes of flooring needed." },
      { slug: "tile-calculator", name: "Tile Calculator", description: "Tiles for an area." },
      { slug: "fence-calculator", name: "Fence Calculator", description: "Posts and panels needed." },
      { slug: "wallpaper-calculator", name: "Wallpaper Calculator", short: "Wallpaper", description: "Rolls of wallpaper." },
      { slug: "mulch-calculator", name: "Mulch & Soil Calculator", short: "Mulch & Soil", description: "Bags of mulch or soil." },
      { slug: "hvac-load-estimator", name: "HVAC Load Estimator", description: "Rough heating/cooling load." },
    ],
  },
  {
    slug: "audio-video",
    name: "Audio & Video",
    short: "Audio/Video",
    emoji: "\u{1F3AC}",
    description: "Convert, compress, trim, mute and extract — all in your browser.",
    status: "live",
    tools: [
      { slug: "audio-trimmer", name: "Audio Trimmer", description: "Audio Trimmer lets you cut a section out of an audio file without installing sof" },
      { slug: "screen-recorder", name: "Screen Recorder", description: "This screen recorder captures your screen, a single window, or a browser tab dir" },
      { slug: "voice-recorder", name: "Voice Recorder", description: "This voice recorder captures audio straight from your device's microphone using " },
      { slug: "video-converter", name: "Video Converter", description: "Convert between MP4, WEBM, MOV, MKV and AVI.", popular: true },
      { slug: "compress-video", name: "Compress Video", description: "Shrink a video's file size.", popular: true },
      { slug: "video-to-gif", name: "Video to GIF", description: "Turn a video clip into an animated GIF." },
      { slug: "resize-video", name: "Resize Video", description: "Change a video's resolution — 1080p to 360p." },
      { slug: "video-to-webp", name: "Video to WebP", description: "Turn a video clip into an animated WebP." },
      { slug: "add-subtitles", name: "Add Subtitles to Video", short: "Add Subtitles", description: "Burn in or attach an .srt subtitle file." },
      { slug: "video-to-text", name: "Video & Audio to Text", short: "Video/Audio to Text", description: "Transcribe speech to text and subtitles." },
      { slug: "audio-converter", name: "Audio Converter", description: "Convert audio to MP3, WAV, M4A, OGG or FLAC." },
      { slug: "video-to-audio", name: "Video to Audio (MP3)", short: "Video to Audio", description: "Extract the soundtrack from a video as MP3." },
      { slug: "mute-video", name: "Mute Video", description: "Remove the audio from a video." },
      { slug: "video-trim", name: "Trim Video", description: "Cut a clip from a video by start and end." },
      { slug: "audio-trim", name: "Trim Audio", description: "Cut a section out of an audio file." },
      { slug: "audio-merge", name: "Merge Audio", description: "Join several audio files into one." },
      { slug: "video-merge", name: "Merge Video", description: "Join several video clips into one." },
    ],
  },
];

// Site-wide category order: these pinned first (in this order), then every other
// category in its natural order above. Used by the menu, homepage tiles and footer.
const MENU_ORDER = ["games", "party", "pdf", "image", "text", "audio-video", "datetime", "calculators", "converters"];
export const categories = rawCategories
  .map((c, i) => [c, i])
  .sort(([a, ai], [b, bi]) => {
    const rank = (slug) => MENU_ORDER.indexOf(slug) + 1 || MENU_ORDER.length + 1;
    return rank(a.slug) - rank(b.slug) || ai - bi;
  })
  .map(([c]) => c);

export function getCategory(slug) {
  return categories.find((c) => c.slug === slug) || null;
}

// Find a tool anywhere in the catalog by slug — used to build cross-category
// "related tools" links. Returns { tool, category } or null.
export function getToolBySlug(slug) {
  for (const c of categories) {
    const t = c.tools.find((x) => x.slug === slug);
    if (t) return { tool: t, category: c };
  }
  return null;
}

export function getTool(categorySlug, toolSlug) {
  const category = getCategory(categorySlug);
  if (!category) return null;
  return category.tools.find((t) => t.slug === toolSlug) || null;
}

// Flat list of every tool, tagged with its category — used by search.
export function allTools() {
  const out = [];
  for (const c of categories) {
    for (const t of c.tools) {
      out.push({
        ...t,
        category: c.slug,
        categoryName: c.name,
        emoji: c.emoji,
        href: `/${c.slug}/${t.slug}`,
      });
    }
  }
  return out;
}
