// Numbered "How to use" steps per built tool (slug -> [step, ...]).
// Rendered as an on-page <ol> under an H2. On-page numbered lists are what Google
// lifts into "featured snippets"; HowTo rich-result *markup* was deprecated in 2023,
// so there's deliberately no HowTo JSON-LD here — the visible list is the win.
export const toolHowto = {
  "2048": ["Slide all tiles one way with arrow keys, WASD, or swipe","Merge two touching tiles of the same number to double them","Keep combining tiles until one reaches 2048","Continue past 2048 to chase a higher score"],
  "merge-pdf": ["Add two or more PDF files from your device","Drag the files into the order you want them combined","Click merge, then download the single joined PDF"],
  "word-to-pdf": ["Upload your Word .docx file","Preview how the converted page will look","Save and download the finished PDF"],
  "pdf-to-jpg": ["Upload a PDF file from your device","Let the tool render one JPG per page","Download the images individually or all at once"],
  "qr-code-scanner": ["Upload a photo or screenshot of a QR code, or start your camera","Wait for the code to be decoded on your device","Copy the decoded text or open the link"],
  "video-to-audio": ["Upload a video file from your device","Choose an output format: MP3, M4A, or WAV","Extract and download just the audio track"],
  "compress-video": ["Upload the video you want to shrink","Choose how hard to compress it","Download the smaller re-encoded MP4"],
  "video-converter": ["Upload a video file from your device","Pick the target format: MP4, WEBM, MOV, MKV, or AVI","Convert and download the re-encoded video"],
  "mute-video": ["Upload the video you want silenced","Let the tool strip the audio without touching the picture","Download the muted copy in the same format"],
  "video-to-gif": ["Upload a short MP4, MOV, or WEBM clip","Set the frame rate and output size","Generate and download the animated GIF"],
  "resize-video": ["Upload a video file from your device","Pick a target resolution: 1080p, 720p, 480p, or 360p","Download the resized H.264 MP4"],
  "video-to-webp": ["Upload a short video clip","Choose the frame rate and size for the animation","Download the compact animated WebP"],
  "add-subtitles": ["Upload your video and a .srt, .vtt, or .ass subtitle file","Choose to burn the text in or attach it as a switchable track","Process and download the subtitled video"],
  "black-and-white": ["Upload the color photo you want to convert","Let the tool strip the color to greyscale","Download the black and white image"],
  "sepia-image": ["Upload the photo you want to tint","Apply the warm brown sepia tone","Download the vintage-looking image"],
  "invert-colors": ["Upload the image you want to flip","Invert every color into its photo-negative opposite","Download the negative image"],
  "blur-image": ["Upload the photo you want to soften","Adjust the blur strength from light haze to heavy","Download the blurred image"],
  "sharpen-image": ["Upload the soft or blurry photo","Raise edge contrast to sharpen the details","Download the crisper image"],
  "pixelate-image": ["Upload the image you want to censor","Select the area to cover and how coarse the blocks should be","Download the picture with the mosaic applied"],
  "add-border-to-image": ["Upload the picture you want to frame","Set the border width and pick a color","Download the image with its solid frame"],
  "add-text-to-image": ["Upload the picture you want to caption","Type your text and set its position, size, and color","Download the captioned image"],
  "round-image": ["Upload the picture you want to crop","Let the tool cut it into a centered circle","Download the round PNG with a transparent background"],
  "pfp-maker": ["Upload the photo you want as your profile picture","Choose a circle, rounded square, or square crop","Set a solid or gradient background and adjust zoom","Pick 400, 512, 800, or 1000 pixels and download the PNG"],
  "webp-to-jpg": ["Drop in the .webp image you want to convert","Let the tool redraw it as a standard JPG","Download the .jpg file, ready to share anywhere"],
  "brightness-contrast": ["Upload the photo you want to adjust","Drag the brightness slider to lighten or darken it","Drag the contrast slider to strengthen or soften tones","Watch the live preview, then save the result"],
  "combine-images": ["Add the two or more pictures you want to merge","Choose a side-by-side row or a stacked column","Download the joined images as one file"],
  "collage-maker": ["Add the photos you want in the collage","Let the tool arrange them into an even grid","Download the finished grid as a single image"],
  "pdf-to-png": ["Open the PDF you want to turn into images","Let the tool render every page separately","Download each page as its own PNG file"],
  "pdf-to-text": ["Open the PDF you want to read text from","Let the tool extract the plain, unformatted text","Copy the text into a document or email"],
  "delete-pdf-pages": ["Open the PDF you want to trim","Select the page numbers you want to drop","Download the rebuilt PDF without those pages"],
  "extract-pdf-pages": ["Open the PDF you want a section from","Set the first and last page of the range","Download that range as a new, smaller PDF"],
  "crop-pdf": ["Open the PDF with wide margins to trim","Set how much to cut from all four sides","Download the tightened PDF with margins removed"],
  "add-text-to-pdf": ["Open the PDF and choose the page to mark","Click where you want the text placed","Type your line of text onto the page","Download the updated PDF"],
  "esign-pdf": ["Open the PDF you need to sign","Draw your signature with mouse, trackpad, or finger","Position the signature on the page's signature line","Download the signed PDF"],
  "create-pdf": ["Type or paste your text into the editor","Let the tool lay it out as a PDF","Download the finished PDF document"],
  "xml-to-json": ["Paste your XML document into the input box","Let the built-in parser convert it to JSON","Copy the equivalent JSON for your code or API"],
  "json-to-xml": ["Paste your JSON value into the input box","Let the tool convert it into an XML document","Copy the XML for the system that expects it"],
  "xml-to-csv": ["Paste your list of repeated XML records","Let the tool map each record to a row","Copy or download the CSV for your spreadsheet"],
  "csv-to-xml": ["Paste CSV with a header row of field names","Let the tool make one XML record per line","Copy the XML for the system that needs it"],
  "csv-to-markdown": ["Paste your comma-separated data into the box","Let the tool build a GitHub-style Markdown table","Copy the table into your README or wiki"],
  "csv-to-html": ["Paste your comma-separated data into the box","Let the tool generate a full HTML table element","Copy the markup into your web page or email"],
  "html-to-text": ["Paste your HTML markup into the input box","Let the tool strip out all the tags","Copy the plain readable text that remains"],
  "epoch-converter": ["Paste a Unix timestamp to get a readable date","Or enter a date to get the epoch number back","Read or copy the converted value instantly"],
  "url-parser": ["Paste the URL you want to inspect","Read the protocol, host, path, and query parameters","Copy any part you need for debugging"],
  "json-minify": ["Paste your JSON into the input box","Choose Minify to compact it or Beautify to indent it","Copy the reformatted JSON from the output"],
  "privacy-policy-generator": ["Fill in the form: data collected, cookies, analytics, contact","Answer whether you use tracking or third-party tools","Generate the policy and copy or download the document","Publish the finished policy on your site or app"],
  "nda-generator": ["Enter the parties, confidential information, and agreement terms","Set the effective date and disclosure conditions","Generate the NDA and print or send it to sign"],
  "bill-of-sale": ["Enter the buyer, seller, item description, and sale price","Add the sale date and any condition notes","Generate the bill of sale and print it for both to sign"],
  "csv-to-excel": ["Select or drop your CSV file into the tool","Let it parse the rows into a workbook","Download the converted .xlsx spreadsheet"],
  "excel-to-csv": ["Upload your .xlsx or .xls spreadsheet","Let the tool read the sheet's rows","Download the plain CSV file"],
  "excel-to-json": ["Upload a spreadsheet whose first row holds the column headers","Let it map each row into an object using those keys","Copy or download the resulting JSON array"],
  "json-to-excel": ["Paste a JSON array of objects into the input","Let the tool build columns from the object keys","Download the generated .xlsx spreadsheet"],
  "excel-to-html": ["Upload your .xlsx or .xls file","Let the tool convert the sheet into table markup","Copy the HTML table and paste it into your page"],
  "create-zip": ["Pick or drop the files you want to bundle","Confirm your selected list of files","Click to build and download the .zip archive"],
  "image-splitter": ["Upload the image you want to slice","Set the number of rows and columns for the grid","Split it and download the tiles as a zip"],
  "split-csv": ["Upload the large CSV file you want to divide","Set how many rows each smaller file should hold","Split it and download the pieces as a zip"],
  "extract-pdf-images": ["Upload the PDF containing the images","Let the tool find every embedded picture","Download the extracted images bundled as a zip"],
  "reverse-pdf-pages": ["Upload the PDF with pages in the wrong order","Let the tool flip the page sequence end to end","Download the reversed PDF"],
  "exif-viewer": ["Upload the JPEG photo you want to inspect","Read the camera settings, date, and GPS metadata shown","Decide whether to strip data before sharing the photo"],
  "chart-maker": ["Type or paste rows of labels and values","Let the tool draw the bars from your numbers","Download the finished bar chart as a PNG"],
  "tsv-to-csv": ["Paste your tab-separated rows into the box","Let it swap tabs for commas and quote tricky cells","Copy or download the resulting CSV"],
  "csv-to-tsv": ["Paste your comma-separated data into the input","Let it parse quoted fields and insert tabs between columns","Copy or download the tab-separated output"],
  "html-table-to-csv": ["Paste the HTML markup containing your table","Let it read the first table's header and data cells","Copy or download the CSV rows"],
  "yaml-to-json": ["Paste your YAML into the input box","Let it parse the nested keys, lists, and comments","Copy the converted JSON output"],
  "json-to-yaml": ["Paste your JSON into the input box","Let it produce indented YAML with minimal quoting","Copy the YAML for your config or pipeline"],
  "video-trim": ["Load your video into the browser tool","Set the start and end times for the clip","Pick a fast cut or a frame-accurate cut","Download the trimmed clip"],
  "audio-trim": ["Upload an MP3, WAV, or M4A file from your device","Set the start and end time for the section to keep","Download the trimmed clip in its original format"],
  "audio-merge": ["Add the audio files you want to combine","Drag the tracks into the order they should play","Download the single merged MP3 track"],
  "video-merge": ["Add the video clips you want to join","Arrange the clips into your preferred play order","Download the combined video file"],
  "word-counter": ["Type or paste your text into the box","Read the live word, character, sentence, and paragraph counts","Check the estimated reading time for your content"],
  "percentage-calculator": ["Pick which of the three percentage questions to answer","Enter your two values into the fields","Read the calculated percentage that updates as you type"],
  "character-counter": ["Paste or write your text into the field","Set an optional character limit to track space remaining","Watch the live character, word, and line counts"],
  "length-converter": ["Type the length value you want to convert","Choose the unit to convert from and to","Read the converted length updating live"],
  "unit-converter": ["Pick a category like length, weight, or temperature","Choose your 'from' and 'to' units","Enter a value and read the converted result"],
  "age-calculator": ["Enter your date of birth","See your age in years, months, and days","Check the countdown to your next birthday"],
  "bmi-calculator": ["Switch between metric and imperial units","Enter your height and weight","Read your BMI and its weight category"],
  "loan-calculator": ["Enter the loan amount, interest rate, and term in years","Read your estimated monthly payment","Check the total interest and total amount paid"],
  "mortgage-calculator": ["Enter home price, down payment, rate, and loan term","Read your estimated monthly mortgage payment","Review the total interest and total amount paid"],
  "profit-margin-calculator": ["Enter your product cost and selling price","Read your profit in dollars instantly","Check your profit margin and markup percentages"],
  "gpa-calculator": ["Add a row for each course you took","Pick each course's letter grade and enter its credit hours","Read your weighted GPA on the 4.0 scale"],
  "json-formatter": ["Paste your JSON into the input box","Click Format to pretty-print or Minify to compact it","Copy the result, or read any syntax error shown"],
  "base64-encode-decode": ["Switch between encode and decode mode","Paste or type your text or Base64 string","Copy the converted result with one click"],
  "meta-tag-generator": ["Enter your page title, description, and canonical URL","Add your image URL and keywords","Copy the generated HTML meta tags to paste into your page"],
  "amazon-margin-calculator": ["Enter sale price, product cost, and referral fee percent","Add your FBA fee and any other costs","Read your net profit, margin, and ROI per unit"],
  "concrete-calculator": ["Enter the length, width, and thickness of your pour","Pick a unit for each dimension","Read the volume and number of 25 kg bags needed"],
  "roas-calculator": ["Enter your ad revenue and ad spend","Read your ROAS multiple and ACOS percentage","Add a profit margin to see profit and break-even ROAS"],
  "shopify-fee-calculator": ["Enter your sale price and pick your Shopify plan","Read the processing fee and your net payout","Add product cost to also see profit and margin"],
  "sales-tax-calculator": ["Choose to add tax or remove tax from a total","Enter the amount and the tax rate","Read the tax amount alongside the resulting figure"],
  "grade-calculator": ["Switch between weighted-average mode and needed-final-score mode","Enter each assignment, quiz, and exam score with its weight","Watch results update live and note if weights miss 100%","Read your weighted average or the final-exam score you need"],
  "paint-calculator": ["Enter total wall area, or a wall's length and height","Set the number of coats and your paint's coverage per litre","Add each door or window to subtract about 1.8 square metres","Read how many litres of paint to buy"],
  "keyword-density-checker": ["Paste or type your content into the text box","Let it count total words and rank the top keywords","Read each word's frequency count and density percentage, stop words ignored"],
  "countdown-timer": ["Pick your target date and time","Watch the days, hours, minutes, and seconds tick down live","See it display Time's up! once the target passes"],
  "image-resizer": ["Upload a PNG, JPG, WebP, or GIF from your device","Type a new width and height, keeping proportions locked if wanted","Download the resized image as a clean PNG"],
  "image-compressor": ["Upload a JPEG or PNG photo","Drag the quality slider and watch the file size drop","Compare original size, compressed size, and percentage saved","Download the smaller JPEG with one click"],
  "instagram-image-resizer": ["Upload the photo you want sized for Instagram","Pick a preset: Square, Portrait, Landscape, or Story","Let it fill the frame and center-crop the overflow","Download the ready-to-post JPEG"],
  "qr-code-generator": ["Type or paste a URL, phone number, Wi-Fi string, or text","Pick a size (256, 512, or 1024) and error-correction level","Watch the code update instantly as you type","Download the crisp PNG for your poster, card, or label"],
  "wifi-qr-generator": ["Enter your network name, password, and encryption type","Download the generated QR code as a crisp PNG","Print or share it so guests scan to join instantly"],
  "compress-pdf": ["Upload any PDF from your device","Let it re-pack and de-duplicate the internal objects locally","Review the original size, new size, and percent change","Download the smaller PDF"],
  "typing-speed-test": ["Pick a sample paragraph from over a hundred options","Start typing as characters highlight green for correct, red for mistakes","Read your words per minute, accuracy, and time when finished"],
  "sudoku": ["Start a new game and choose your difficulty","Fill the blank cells with digits 1 to 9","Check your work or reveal the full solution anytime"],
  "invoice-generator": ["Fill in your business and client details","Add line items and set a tax rate","Watch the subtotal, tax, and total update in the live preview","Download the print-ready invoice as a PDF"],
  "crop-image": ["Upload the photo you want to trim","Type precise X, Y, width, and height values in pixels","Check the live overlay showing the region you're keeping","Click Crop and Download to save at full resolution"],
  "split-pdf": ["Load a PDF to see its total page count","Type a range like 1-3, 5, 8-10 to extract those pages","Or split the whole document into one file per page","Download the resulting PDF or pages"],
  "tip-calculator": ["Enter your bill amount","Pick a tip percentage button or type your own","Set the number of people splitting the bill","Read the tip, grand total, and per-person share"],
  "temperature-converter": ["Pick your From and To units among Celsius, Fahrenheit, Kelvin","Type a number to convert","Read the live result plus all three scales at once"],
  "case-converter": ["Paste your text into the box","Pick a mode like UPPERCASE, Title Case, camelCase, or snake_case","Copy the converted result with one click","Check the live character, word, and line count"],
  "reading-time-calculator": ["Paste or type your text into the box","Choose a reading pace: Slow, Average, or Fast","Read the estimated reading and out-loud speaking time live"],
  "date-difference": ["Enter a start date and an end date","Read the total days between them, order-independent","See the span broken into years, months, days, and weeks"],
  "compound-interest-calculator": ["Enter your principal, annual rate, and number of years","Choose how often interest compounds, annually through daily","Add an optional monthly contribution","Read your final balance, total contributions, and interest earned"],
  "password-generator": ["Pick a length from 6 to 64","Choose which character types to include: uppercase, lowercase, numbers, symbols","Optionally exclude look-alike characters like l, 1, I, O, 0","Generate the password and check its live strength rating"],
  "markup-calculator": ["Choose a mode: cost plus markup, or cost plus sale price","Enter the item cost in the first field","Type the markup percentage or the target sale price","Read the sale price, profit, and profit margin instantly"],
  "serp-snippet-preview": ["Type your page title, URL, and meta description","Watch the Google-style desktop result card render live","Check the length warnings flagging titles or descriptions cut off","Adjust your text until the snippet displays in full"],
  "hashtag-generator": ["Enter a topic or a few keywords","Generate the tag set with case and combined variations","Copy the deduplicated list, capped at Instagram's 30 max"],
  "etsy-fee-calculator": ["Enter your item price and shipping charged","Add optional item and shipping costs","Review the listing, transaction, and processing fees broken out","See your net profit and profit margin after Etsy's cut"],
  "quote-calculator": ["Add line items with description, quantity, and unit price","Set a percentage or flat-dollar discount","Enter your tax rate applied to the discounted subtotal","Read the currency-formatted subtotal, discount, tax, and total"],
  "flooring-calculator": ["Enter the room length and width in feet or meters","Choose a waste allowance and coverage per box","Read the floor area and exact number of boxes to buy"],
  "png-to-jpg": ["Upload a PNG or other image file","Drag the quality slider to balance size and clarity","Compare original versus output size before downloading the JPEG"],
  "jpg-to-pdf": ["Upload one or more JPG, PNG, or WebP files","Reorder pages with the up, down, and remove controls","Download the single PDF, one image sized per page"],
  "discount-calculator": ["Enter the original price of the item","Pick a percentage or fixed-dollar discount and type it","Read your savings, final price, and effective percent off"],
  "weight-converter": ["Enter a value and pick your From and To units","Read the converted weight and plain-English sentence instantly","Tap the swap button to reverse the conversion without retyping"],
  "url-qr-generator": ["Type any website URL, https added automatically if missing","Pick the QR code size you need","Download the crisp PNG for flyers, cards, or menus"],
  "fancy-font-generator": ["Type your text once in the input box","Scan the Bold, Script, Circled, and other styled rows","Click Copy on a style to paste into bios or captions"],
  "time-zone-converter": ["See your current local time on the live clock at the top (it auto-detects your zone)","Enter a date and wall-clock time to convert","Pick the source zone and the target zone","Read the matching moment, UTC offsets, and time difference"],
  "salary-calculator": ["Enter a pay amount and select its pay period","Adjust hours per week, days per week, and weeks per year","Read hourly, daily, weekly, monthly, and annual equivalents"],
  "schema-generator": ["Pick a schema type like Organization, Product, or FAQ Page","Fill in only the fields shown for that type","Copy the live JSON-LD script tag into your HTML"],
  "hash-generator": ["Paste or type any text into the box","Watch MD5, SHA-1, SHA-256, and SHA-512 recompute live","Click Copy beside the digest you need"],
  "break-even-calculator": ["Enter your fixed costs for the period","Add the price per unit and variable cost per unit","Read the break-even point in units, revenue, and contribution margin"],
  "tweet-character-counter": ["Paste or type your post text","Toggle between the 280 and 4,000-character Premium limits","Watch used, remaining, and the bar turn red when over"],
  "price-after-fees-calculator": ["Enter your sale price","Add the percentage fee and the fixed per-transaction fee","Read total fees and your exact net payout"],
  "receipt-generator": ["Enter your business name, date, and payment method","Add line items with quantity and unit price, then set tax rate","Watch the printable receipt preview update with subtotal and total"],
  "wordle": ["Type a five-letter guess with your keyboard or on-screen keys","Read the green, yellow, and grey letter clues","Refine your next guess across up to six tries"],
  "tile-calculator": ["Enter the area length and width in feet or meters","Set your tile size in centimeters and a waste allowance","Add optional tiles-per-box to get total tiles and boxes needed"],
  "rotate-pdf": ["Upload the PDF you want to reorient","Pick a rotation angle of 90, 180, or 270 degrees clockwise","Download the corrected PDF with every page turned"],
  "jpg-to-png": ["Drop in a JPG, WebP, GIF, or BMP image","Let it redraw the image and export a lossless PNG","Check the size and dimension stats, then download the PNG"],
  "citation-formatter": ["Choose the source type: website, book, or journal article","Enter the author, title, year, publisher, URL, and access date","Copy the generated APA, MLA, or Chicago reference block"],
  "average-calculator": ["Paste your numbers separated by commas, spaces, or new lines","Read the mean, median, mode, and full statistics instantly","Ignore stray non-numeric tokens; they are skipped automatically"],
  "color-converter": ["Type a hex code or pick a color with the swatch picker","Watch the RGB, HSL, and preview update in real time","Copy the converted values or tweak the RGB channels by hand"],
  "url-encode-decode": ["Paste the text or URL you need to escape or unescape","Choose Component mode for one value or Full URL mode","Read the encoded or decoded output and copy it out"],
  "minesweeper": ["Choose a Beginner or Intermediate difficulty board","Left-click cells to reveal them; your first click is always safe","Right-click or use Flag Mode to mark suspected mines"],
  "sip-calculator": ["Enter your fixed monthly investment amount","Set the expected annual return and number of years","Read the total invested, estimated returns, and projected value"],
  "reorder-pages": ["Drop in a PDF to load its numbered page rows","Use the up, down, and remove controls to arrange pages","Save to build and download a fresh PDF in your order"],
  "watermark-pdf": ["Upload your PDF and type the watermark text","Set the font size, opacity, and diagonal or banded position","Download the stamped PDF applied across every page"],
  "image-to-webp": ["Upload a PNG, JPG, GIF, or BMP image","Adjust the quality slider and watch the size savings","Download the optimized .webp file"],
  "rotate-image": ["Upload the picture you want to turn or mirror","Rotate left or right in 90-degree steps, or flip it","Download the result as a clean PNG"],
  "random-number-generator": ["Set the minimum, maximum, and how many numbers you need","Choose whether repeated values are allowed","Generate the numbers, then copy or regenerate them"],
  "lorem-ipsum-generator": ["Pick paragraphs, sentences, or words as the unit","Set the count and optionally start with the classic opening","Generate the placeholder text and copy it into your project"],
  "text-diff": ["Paste the original version into the left box","Paste the changed version into the right box","Read the green additions and red removals with change counts"],
  "scientific-calculator": ["Enter an expression with the button pad or your keyboard","Toggle Deg or Rad to control how angles are read","Read the parsed result for powers, roots, logs, or trig"],
  "number-base-converter": ["Enter a number and pick its base: binary, octal, decimal, or hex","See the value converted into all four bases at once","Copy any result with its own Copy button"],
  "csv-to-json": ["Paste your raw CSV data into the input box","Choose the delimiter and toggle whether row one is a header","Read the pretty-printed JSON output and row count"],
  "whatsapp-qr-generator": ["Enter the phone number and an optional pre-filled message","Generate the scannable QR code and wa.me link","Share the code so scanners open a ready WhatsApp chat"],
  "vcard-qr-generator": ["Fill in your name, phone, email, organization, and address","Generate the QR code that encodes a vCard 3.0 file","Let scanners point their camera to save you as a contact"],
  "gst-vat-calculator": ["Enter the amount and pick a rate preset or type your own","Choose whether to add tax to net or remove it from gross","Read the tax amount with net and gross totals"],
  "uuid-generator": ["Pick how many version 4 UUIDs you need","Toggle uppercase output or strip the hyphens","Copy all UUIDs at once or regenerate a fresh batch"],
  "pomodoro-timer": ["Set your focus, short break, and long break lengths","Press start to count down the session in MM:SS","Let it auto-cycle into breaks and count completed sessions"],
  "regex-tester": ["Type your regular expression into the pattern field","Toggle the global, ignore-case, multiline, and dotall flags","Paste test text to see matches highlighted with capture groups"],
  "robots-txt-generator": ["Choose an allow-all, block-all, or custom mode","Set user-agent, Disallow and Allow paths, crawl-delay, and sitemap","Copy or download the generated robots.txt file"],
  "conversion-rate-calculator": ["Enter your total visitors and number of conversions","Read your conversion rate as a percentage instantly","Add revenue and cost figures for net profit and ROI"],
  "bio-character-counter": ["Pick your platform to load the correct bio limit","Type your bio to count characters used and remaining","Trim your text when the numbers turn red"],
  "dropshipping-profit-calculator": ["Enter selling price, product cost, shipping, fee percent, and ad cost","See profit per order and profit margin instantly","Add monthly orders to project monthly profit and revenue"],
  "reaction-time-test": ["Click to start, then wait for the box to turn green","Click as fast as you can once green appears","Repeat five rounds to see your best and average"],
  "cps-test": ["Pick a duration of 1, 5, 10, or 60 seconds","Click the play area rapidly; the first click starts timing","View your total clicks, clicks per second, and speed rating"],
  "random-picker": ["Paste your list with one item per line","Set how many items you want to pick","Press the button to reveal fair, unique winners"],
  "estimate-template": ["Fill in your business, client, and estimate details","Add line items with descriptions, quantities, and unit prices","Set optional tax, then print or save as PDF"],
  "fence-calculator": ["Enter fence length, post spacing, and rails per section","Add any gates to subtract their width from the run","Read the posts, sections, and rails you need"],
  "add-page-numbers": ["Upload the PDF you want to number","Choose position, start number, font size, and label format","Download the fresh PDF with numbers on every page"],
  "webp-to-png": ["Drag and drop or choose your .webp image","Preview the converted PNG with sizes and dimensions","Download the lossless PNG with transparency preserved"],
  "ratio-calculator": ["Enter three values of A : B = C : D","Leave one box blank to solve the missing number","Switch to simplify mode to reduce a ratio fully"],
  "find-and-replace": ["Paste your source text into the tool","Type what to find and what to replace it with","Toggle match case, whole word, or regex mode","Copy the updated text with its replacement count"],
  "svg-to-png": ["Upload an .svg file or paste your SVG markup","Pick an output width and a background color","Download the rasterized PNG at your chosen size"],
  "sort-lines": ["Paste your list of lines into the box","Choose alphabetical, numeric, reverse, or shuffle order","Toggle case-insensitivity, trimming, or removing blank lines","Copy the reordered result with one click"],
  "json-to-csv": ["Paste a JSON array of objects into the input","Let it build CSV columns from every object's keys","Copy or download the spreadsheet-ready .csv file"],
  "roman-numeral-converter": ["Type a whole number from 1 to 3999","Read its Roman numeral, converted live as you type","Enter a Roman numeral instead to decode its value"],
  "email-qr-generator": ["Enter the recipient address, subject line, and message","Generate the QR code encoding that pre-filled email","Download or print it for cards, flyers, or signage"],
  "stopwatch": ["Press start to time in hours, minutes, seconds, and centiseconds","Record laps to capture splits without stopping the clock","Stop to pause, resume to continue, or reset to clear"],
  "simple-interest-calculator": ["Enter your principal, annual interest rate, and time in years","View the interest earned from principal times rate times time","Read your total amount, formatted as clean currency"],
  "add-subtract-days": ["Pick a start date and choose add or subtract mode","Enter a number of days, weeks, months, or years","Read the resulting date and its day of the week","Switch modes to count days between two dates instead"],
  "roi-calculator": ["Enter the amount invested and the amount you got back","Add an optional holding period in years for annualized ROI","Read your ROI percent, net profit, and total returned"],
  "jwt-decoder": ["Paste your JSON Web Token into the input box","View the decoded header and payload as pretty-printed JSON","Check the algorithm and the expired-or-valid claim badge"],
  "slug-generator": ["Type any title, heading, or phrase into the field","Choose a hyphen or underscore separator and toggle lowercasing","Copy the clean URL-safe slug it builds as you type"],
  "color-picker": ["Pick a color on the wheel or type a HEX code","Read the HEX, RGB, HSL values and complementary color","Click any value's copy button to grab it"],
  "cpm-calculator": ["Choose whether to solve for cost, impressions, or CPM","Enter the two known values and pick your currency","Read the computed third value in the stat grid"],
  "utm-builder": ["Enter your base URL, utm_source, utm_medium, and utm_campaign","Fill optional utm_term and utm_content fields if needed","Copy the tagged, URL-encoded campaign link in one click"],
  "caption-formatter": ["Paste your caption to see live character and hashtag counts","Toggle Instagram line-breaks and add bullet points as needed","Copy the finished, formatted caption with one button"],
  "sku-generator": ["Enter a product prefix and attribute lists like colors and sizes","Set your separator, running number, zero-padding, and uppercase options","Generate every combination as clean SKU codes to copy"],
  "hangman": ["Guess one letter at a time for the hidden word","Watch correct letters fill blanks and wrong ones draw the figure","Solve it within six wrong guesses to win","Click New Word to start a fresh puzzle"],
  "hourly-rate-calculator": ["Enter your desired annual take-home income and business expenses","Add billable hours per week and weeks worked per year","Read the minimum hourly rate you need to charge"],
  "coin-flip": ["Click Flip the coin to spin it","See whether it lands on Heads or Tails","Watch the running tally track your results across flips"],
  "dice-roll": ["Pick whether to roll one, two, or three dice","Hit Roll to tumble them to a random result","Read each die and the automatic combined total"],
  "wheel-of-names": ["Type your names or options, one per line","Spin the wheel to land on a random winner","Remove the winner and spin again for the next draw"],
  "firewood-calculator": ["Enter the stack's length, height, and log depth","Read the volume in full cords, cubic feet, and metres","See what a face cord means for your log length"],
  "yeast-converter": ["Enter an amount in grams or packets","Choose the yeast type you have on hand","Read the equivalent active dry, instant, and fresh amounts"],
  "thread-size-converter": ["Enter a thread value in any system like Tex or denier","Read the equivalent Nm, Ne, ticket, and embroidery weight","Check the label showing which systems run finer with higher numbers"],
  "bead-size-converter": ["Pick a seed bead size in the aught system","Read the round and cylinder Delica millimetre sizes side by side","Check how many beads fit per inch"],
  "pipe-size-converter": ["Enter a pipe size as NPS, DN, or actual OD","Read the equivalent sizes in millimetres and inches","Note where nominal size stops matching the real diameter"],
  "battery-equivalents": ["Type a battery code like LR44, 357, or CR2032","See every interchangeable brand and standard name for that cell","Check its size, voltage, chemistry, and any fit warnings"],
  "bulb-base-converter": ["Pick a bulb base code like E26, GU10, or B22","Read its thread or pin size, common name, and voltage","Check which bases it can and can't swap with"],
  "cups-to-grams-converter": ["Pick your ingredient like flour, sugar, butter, or cocoa","Enter the amount in cups, tablespoons, grams, or ounces","Read the accurate weight for that specific ingredient"],
  "oven-temperature-converter": ["Type a temperature into any field: °F, °C, gas mark, or fan","Read the matching values fill in across all four systems instantly","Scroll the full chart to compare fan-oven and gas-mark equivalents"],
  "pan-size-converter": ["Enter the pan your recipe calls for: round, square, or rectangular","Enter the pan you actually own and its dimensions","Read the base-area comparison and the exact ingredient scaling factor"],
  "paper-size-converter": ["Pick a paper size from the A, B, C, or US series","Read its dimensions in millimetres, centimetres, and inches","Copy the print-scaling percentage to fit it onto another size"],
  "kids-clothing-size-converter": ["Switch between baby, kids clothing, or kids shoes","Pick the size system you know and enter the size","Read the US, UK, and EU equivalents plus the height in centimetres"],
  "sheet-metal-gauge-converter": ["Choose your metal: steel, galvanised, stainless, or aluminium","Select a gauge, or enter a thickness to find the nearest gauge","Read the exact thickness in millimetres and inches for that metal"],
  "ring-size-converter": ["Enter a ring size in US, UK, EU, or Japan, or a mm measurement","See every system's equivalent calculated at once","Scroll the full chart to check diameter and circumference values"],
  "bra-size-converter": ["Pick the system and choose your band and cup to convert","Or switch to the calculator and enter under-bust and bust measurements","Read your size matched across US, UK, EU, French, and Australian systems"],
  "drill-bit-size-converter": ["Select a standard size, or type a measurement to find the nearest drill","See fractional, decimal, metric, number, and letter equivalents","Check the tap-drill reference chart for matching thread sizes"],
  "knitting-crochet-converter": ["Switch between knitting needles and crochet hooks","Pick a size in US, UK/Canadian, or metric millimetres","Read the equivalents, using the full chart for exact matches"],
  "clothing-size-converter": ["Choose women's or men's clothing, or women's or men's shoes","Pick the sizing system you know and enter your size","Read the equivalent in every other system plus the full chart"],
  "yes-no-wheel": ["Type in your yes-or-no question if you like","Spin the wheel and watch it decelerate between the segments","Read whether it lands on YES or NO"],
  "tic-tac-toe": ["Choose two-player mode or the unbeatable computer opponent","Tap squares on the 3x3 grid to place your marks","Watch it detect the win or draw and update the scoreboard"],
  "flashcard-generator": ["Add term-and-definition pairs, or paste a whole list to import at once","Flip into Study mode to review one card at a time","Click cards to flip them, then shuffle or mark them known"],
  "wallpaper-calculator": ["Enter your wall width and height, roll size, and pattern repeat","Subtract the number of doors and windows in the room","Read how many rolls to buy after pattern-repeat waste"],
  "fraction-calculator": ["Enter a numerator and denominator for each of the two fractions","Pick add, subtract, multiply, or divide","Read the reduced answer as an improper fraction, mixed number, and decimal"],
  "favicon-generator": ["Upload a picture or logo to draw onto square canvases","Choose a transparent or solid background and preview each size","Download the PNGs and copy the ready-made HTML"],
  "remove-duplicate-lines": ["Paste your list of text into the box","Toggle case-insensitive matching, whitespace trimming, or blank-line removal","Copy the cleaned list keeping each line's first occurrence"],
  "business-days-calculator": ["Choose counting mode or add mode","Enter your dates, or a start date and a number of business days","Add any holidays, then read the working-day total or resulting date"],
  "number-to-words": ["Type any number, or switch on currency mode for dollars and cents","Pick lowercase, Sentence case, Title Case, or UPPERCASE","Copy the spelled-out words with one click"],
  "inflation-calculator": ["Enter an amount, a start year, and an end year","Set the average annual inflation rate to compound","Read the equivalent value and total percentage price change"],
  "canonical-tag-generator": ["Paste the page URL to validate and normalize","Choose to strip tracking parameters, fragments, or trailing slashes","Copy the canonical link tag and optional og:url meta tag"],
  "cac-calculator": ["Enter your total sales and marketing spend and new customers acquired","Add an optional lifetime value and pick your currency","Read your CAC, LTV:CAC ratio, and net value per customer"],
  "html-minifier": ["Paste your HTML markup into the input box","Run the minifier to strip comments and collapse whitespace","Review the bytes saved, then copy the minified HTML"],
  "youtube-thumbnail-resizer": ["Upload any image you want as a thumbnail","Adjust zoom and JPG quality using the live crop preview","Download the finished 1280x720 thumbnail"],
  "product-title-counter": ["Type your product title into the field","Watch the live counts for Amazon, eBay, Etsy, and Shopify","Trim until every marketplace shows an under indicator"],
  "appointment-slot-generator": ["Set your day start and end times","Choose appointment length, buffer, and an optional lunch break","Generate the slots, then copy or download the list"],
  "word-search": ["Enter your own word list or load the sample","Pick a grid size and toggle diagonal placement","Generate the puzzle, then print or make a new one"],
  "study-planner": ["Enter your deadline, subjects, and daily study hours","Generate the day-by-day schedule spread to your due date","Copy the plan or download it as a CSV"],
  "mulch-calculator": ["Enter your bed length and width, or a total area","Set the mulch depth in inches and your bag size","Read the cubic yards needed and number of bags to buy"],
  "image-to-base64": ["Drop or select a PNG, JPG, SVG, or WebP file","Grab the generated data URI, img tag, or CSS snippet","Click copy to paste it into your code"],
  "calorie-calculator": ["Enter your age, sex, height, and weight","Pick your activity level and metric or imperial units","Read your maintenance, weight-loss, and weight-gain targets"],
  "text-reverser": ["Paste your text into the input box","View the character, word-order, and line-order reversals","Copy whichever reversed result you need"],
  "work-hours-calculator": ["Enter your clock-in, clock-out, and unpaid break","Toggle overnight shift and add an hourly rate if needed","Read your total worked hours and estimated gross pay"],
  "savings-goal-calculator": ["Enter your goal, current savings, and monthly contribution","Add your annual interest rate","See how many months and years until you hit the target"],
  "llms-txt-generator": ["Enter your site name and a short summary","Add your key links and group them into sections","Copy the generated llms.txt file to your site root"],
  "css-minifier": ["Paste your stylesheet into the input area","Minify to strip comments and tighten braces and spacing","Check the percentage saved and copy the compact CSS"],
  "engagement-rate-calculator": ["Enter your followers, likes, comments, and shares or saves","Optionally add reach for a by-reach rate","Read your engagement percentage against the benchmark"],
  "cpa-calculator": ["Enter your total ad spend and number of conversions","Or switch to clicks-and-conversion-rate mode and pick a currency","Read your cost per acquisition and cost per click"],
  "memory-match": ["Choose a difficulty to set the grid size","Flip two cards at a time to find matching emoji pairs","Clear the board in the fewest moves and fastest time"],
  "slugify": ["Paste your list of titles, one per line","Choose a hyphen or underscore separator","Copy every clean URL slug with one click"],
  "meme-generator": ["Upload the picture you want to caption","Type your top and bottom text and tweak the font and colors","Download the finished meme as a full-resolution PNG"],
  "morse-code-translator": ["Type plain text or Morse code into the box","Let it auto-detect the direction, or lock it yourself","Read the translation or press Play to hear the beeps"],
  "week-number": ["Pick any date to see its ISO week number","Read the week-year, day-of-year, and Monday-to-Sunday range","Switch to reverse mode to turn a week number into dates"],
  "cron-generator": ["Set each field or start from a quick preset","Choose every interval, a specific value, or a step like */5","Copy the cron expression and its plain-English summary"],
  "js-minifier": ["Paste your JavaScript source into the input box","Run the minify to strip comments, trim lines, and drop blanks","Compare the original versus minified byte size and percent saved","Copy the smaller output for your production script"],
  "link-in-bio-qr": ["Paste your Linktree, Instagram, or TikTok bio URL","Tap a preset button to prefill the https:// prefix","Add an optional label beneath the code","Download the high-resolution PNG for print or packaging"],
  "hvac-load-estimator": ["Enter floor area, ceiling height, and climate zone","Set sun exposure, occupant count, and number of windows","Read the estimated cooling BTU/hr and suggested AC tonnage","Check the ballpark furnace size for heating"],
  "landing-page-roi-calculator": ["Enter monthly visitors, conversion rate, and average order value","Read your monthly conversions, monthly revenue, and annual revenue","Add an improved conversion rate to project the uplift","Compare the extra monthly and annual revenue from the same traffic"],
  "email-subject-line-tester": ["Type your email subject line into the field","Watch the live score out of 100 update as you type","Review flags for length, ALL-CAPS, spam words, and emoji","Revise until length hits the 30-50 character sweet spot"],
  "heic-to-jpg": ["Upload the .heic photo from your iPhone","Choose JPG or PNG output and set the quality","Download the converted image, processed on your device"],
  "barcode-generator": ["Type the value you want encoded","Pick a barcode type such as CODE128, EAN-13, or UPC","Download the crisp scannable PNG"],
  "markdown-to-html": ["Type or paste your Markdown into the editor","Watch the live preview render it instantly","Copy the clean HTML source to paste anywhere"],
  "image-to-text": ["Upload a screenshot, document photo, receipt, or sign","Let the on-device OCR engine read the words","Copy the selectable extracted text in seconds"],
  "solitaire": ["Deal a fresh Klondike hand in your browser","Build the four foundations up from Ace to King by suit","Stack tableau columns down in alternating colours to clear the board"],
  "protect-pdf": ["Upload the PDF you want to lock","Set a strong open password with AES-256 encryption","Optionally restrict printing, copying, and editing","Download the protected file, processed locally"],
  "video-to-text": ["Upload any audio or video file","Let the in-browser model transcribe the speech","Copy the transcript or download .srt and .vtt subtitles"],
  "audio-converter": ["Upload the audio file you want to convert","Choose an output format: MP3, WAV, M4A, OGG, or FLAC","Set the bitrate when exporting to MP3","Download the converted audio, encoded on your device"],
  "team-generator": ["Type or paste your names into the box, one name per line.","Choose Number of teams or Players per team, then enter a number.","Press Make teams to shuffle and split everyone into balanced groups.","Use Copy all to copy every team, or press Make teams again to reshuffle."],
  "random-turn-order": ["Type or paste your names into the box, one per line.","Press Shuffle order to arrange everyone into a random sequence.","Read the numbered order from first to last, top to bottom.","Press Copy order to share it, or Re-shuffle order for a new sequence."],
  "truth-or-dare": ["Tap Truth for a question, Dare for a challenge, or Random to pick one at random.","Read the prompt out loud and take your turn.","Press Next (or Surprise me) to draw the following prompt for the next player.","Use Copy to grab the current prompt if you want to share or save it."],
  "would-you-rather": ["Press Start to reveal your first would-you-rather dilemma.","Read both options out loud and let everyone pick a side.","Tap Next question to draw a new dilemma for the next round.","Use Copy to save or share the current question."],
  "never-have-i-ever": ["Gather your group and have everyone hold up ten fingers.","Press Next to reveal a random statement and read it aloud.","Anyone who has done it puts one finger down.","Keep pressing Next until one player is left with a finger up — they win."],
  "most-likely-to": ["Gather your group in a circle or around a table.","Press Next to reveal a random prompt and read it out loud.","On the count of three, everyone points at the person who fits best.","Tally the points and move on to the next prompt for a new round."],
  "charades-generator": ["Choose a category and, if you like, a difficulty level.","Press Start, then New word to draw a word to act out.","Hand the device to the actor and tap the panel to reveal the word.","Act it out for the group, then press New word for the next turn."],
  "pictionary-generator": ["Choose a category and a difficulty level.","Press Start drawing to reveal a word for the drawer.","Sketch the word with no letters, numbers, or talking while others guess.","Press New word to move on to the next round."],
  "heads-up-generator": ["Choose a category from the dropdown.","Press Start and hold your phone to your forehead, screen facing the group.","Let everyone act out or describe the word while you guess it out loud.","Tap New word to move on to the next round."],
  "scattergories-generator": ["Choose whether to exclude the hard letters, then press Roll letter & list.","Read out the letter and the twelve categories to all players.","Start the 60-second timer and have everyone write an answer for each category.","When time is up, compare lists and score one point per valid answer."],
  "trivia-generator": ["Choose a category from the dropdown.","Press \"Start\" or \"Next question\" to show a random question.","Let everyone guess out loud, then press \"Reveal answer\" to check.","Tap \"Copy\" to save a question and its answer, or press \"Next question\" to keep playing."],
  "icebreaker-generator": ["Pick a category that matches the group and mood.","Press \"Start\" or \"Next\" to reveal a random conversation starter.","Read it aloud and invite everyone to share an answer.","Press \"Next\" for another, or \"Copy\" to save the one on screen."],
  "bingo-card-generator": ["Choose a card type — “Numbers (1–75 classic)” or “Custom words”.","For word cards, paste at least 24 words, one per line or separated by commas.","Press “New card” to generate a fresh 5×5 board, repeating for each player.","Press Ctrl+P or Cmd+P to print the card or save it as a PDF."],
  "group-scoreboard": ["Type a player or team name and press Add (or hit Enter).","Use the −1, +1 and +5 buttons on each row to adjust scores.","Watch the leaderboard re-sort automatically with the leader on top.","Use “Reset scores” to zero everyone or “Remove all” to start fresh."],
  "spin-the-bottle": ["Optionally type one player name per line in the box.","Press “Spin the bottle” and watch it turn.","Read who the bottle lands on, or the direction it points.","Press again for the next round, or Reset to start over."],
  "team-name-generator": ["Choose a theme from the dropdown.","Press “Generate names” to get eight team names.","Tap “Copy” on any name you want to keep.","Press “Generate more” for a fresh batch."],
  "secret-santa-generator": ["Type or paste every participant's name, one per line (at least three).","Press \"Draw names\" to create random Giver → Receiver pairings.","Copy the pairings or re-draw for a different result.","Share each person's match privately so the gift exchange stays a surprise."],
  "mafia-role-assigner": ["Enter the number of players, or tick the option to type player names.","Adjust the Mafia, Detective, and Doctor counts, or press \"Use suggested\".","Press \"Assign roles\" to shuffle roles across all players.","Pass the device around — each player taps their name to reveal, then taps again to hide before passing on."]
};
